-- data_015_limpieza_calles_prefijo_tipo_cruzado.sql
-- Segunda pasada de limpieza (a peticion del usuario): "solo debe traer el nombre y ya",
-- sin NINGUNA palabra de tipo de vialidad dentro de `nombre`, incluso si esa palabra NO
-- coincide con el `tipo_vialidad` propio de la fila (ej. nombre="Calle Insurgentes" con
-- tipo_vialidad="Avenida" -> el front mostraba "Avenida Calle Insurgentes"). La migracion
-- 014 solo cubrio el caso donde el prefijo coincidia con el propio tipo_vialidad; esta
-- cubre cualquier prefijo de cualquiera de los tipos de vialidad conocidos en el catalogo:
-- avenida, calle, andador, circuito, bulevar, privada, callejon, prolongacion, carretera, calzada, retorno, peatonal, continuacion, boulevard, periferico, cerrada
-- Igual que antes: los duplicados resultantes se fusionan (se migran relaciones
-- calles_colonias a la fila canonica) y se desactivan (activo=0, nunca se borran).
-- Generado 2026-08-26T04:37:16.120Z

START TRANSACTION;

-- ============================================
-- 1) RENOMBRES: quitar prefijo de tipo cruzado/ajeno (14)
-- ============================================
UPDATE calles SET nombre = 'Libramiento de Tepic', nombre_normalizado = 'libramiento de tepic' WHERE id = 1199;
UPDATE calles SET nombre = 'Guadalajara - Tepic', nombre_normalizado = 'guadalajara - tepic' WHERE id = 1941;
UPDATE calles SET nombre = 'del Kinder', nombre_normalizado = 'del kinder' WHERE id = 1999;
UPDATE calles SET nombre = 'Pantanal - San Cayetano', nombre_normalizado = 'pantanal - san cayetano' WHERE id = 2018;
UPDATE calles SET nombre = 'General Mariano Ruiz', nombre_normalizado = 'general mariano ruiz' WHERE id = 2030;
UPDATE calles SET nombre = 'Canoa', nombre_normalizado = 'canoa' WHERE id = 2047;
UPDATE calles SET nombre = 'Vulcano', nombre_normalizado = 'vulcano' WHERE id = 2114;
UPDATE calles SET nombre = 'Tepic - Puerto Vallarta', nombre_normalizado = 'tepic - puerto vallarta' WHERE id = 2150;
UPDATE calles SET nombre = 'El Tecolote', nombre_normalizado = 'el tecolote' WHERE id = 2179;
UPDATE calles SET nombre = 'Las Grullas', nombre_normalizado = 'las grullas' WHERE id = 2180;
UPDATE calles SET nombre = '16 de Noviembre', nombre_normalizado = '16 de noviembre' WHERE id = 3181;
UPDATE calles SET nombre = 'de los Ríos', nombre_normalizado = 'de los rios' WHERE id = 3369;
UPDATE calles SET nombre = 'Tecnológico Oriente', nombre_normalizado = 'tecnologico oriente' WHERE id = 3461;
UPDATE calles SET nombre = 'de la Higuera', nombre_normalizado = 'de la higuera' WHERE id = 5810;

-- ============================================
-- 2) FUSIONES: migrar relaciones calles_colonias hacia la fila canonica (89)
-- ============================================
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 4124, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 308 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 4124 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 332, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 807 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 332 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 4871, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 344 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 4871 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 4272, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 345 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 4272 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 3872, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 348 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 3872 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 3150, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 355 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 3150 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 5076, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 357 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 5076 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 4606, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 373 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 4606 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 412, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 410 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 412 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 3896, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 451 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 3896 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 2738, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 466 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 2738 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 511, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1458 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 511 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 5032, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 565 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 5032 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 2479, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 606 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 2479 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 3784, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 613 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 3784 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 1430, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 616 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 1430 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 3684, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 636 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 3684 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 770, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 670 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 770 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 3990, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 703 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 3990 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 771, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 742 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 771 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 4420, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 743 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 4420 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 3553, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 774 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 3553 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 813, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 778 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 813 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 813, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1882 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 813 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 931, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 817 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 931 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 3682, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 827 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 3682 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 891, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 2653 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 891 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 3323, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 945 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 3323 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 4537, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 966 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 4537 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 3851, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 967 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 3851 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 3687, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1005 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 3687 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 1031, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1050 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 1031 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 1032, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1103 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 1032 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 4680, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1058 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 4680 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 4492, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1059 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 4492 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 4478, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1094 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 4478 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 4185, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1114 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 4185 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 1118, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1117 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 1118 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 1134, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1157 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 1134 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 3870, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1145 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 3870 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 1175, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 2564 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 1175 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 4302, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1197 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 4302 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 4302, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1198 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 4302 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 4303, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1217 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 4303 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 1240, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 5647 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 1240 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 4631, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1356 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 4631 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 5086, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1358 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 5086 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 4276, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1400 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 4276 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 5265, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1440 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 5265 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 5265, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1441 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 5265 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 4408, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1457 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 4408 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 1486, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1459 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 1486 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 5090, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1482 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 5090 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 1564, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1495 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 1564 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 1566, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1588 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 1566 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 4290, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1597 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 4290 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 4227, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1599 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 4227 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 4679, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1600 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 4679 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 4814, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1638 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 4814 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 5281, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1650 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 5281 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 3353, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1762 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 3353 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 4031, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1857 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 4031 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 2431, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 1997 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 2431 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 2002, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 2001 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 2002 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 5830, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 2020 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 5830 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 2031, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 2060 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 2031 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 2122, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 3460 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 2122 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 2147, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 2592 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 2147 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 2212, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 2267 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 2212 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 4614, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 2221 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 4614 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 2227, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 2240 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 2227 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 4686, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 2338 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 4686 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 5386, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 2581 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 5386 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 2619, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 2621 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 2619 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 2619, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 4936 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 2619 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 4393, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 2688 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 4393 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 3866, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 2723 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 3866 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 5781, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 2994 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 5781 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 4305, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 3041 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 4305 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 4054, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 3076 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 4054 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 3186, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 5779 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 3186 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 3223, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 3364 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 3223 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 3238, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 3365 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 3238 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 3255, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 3366 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 3255 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 3535, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 3459 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 3535 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 3480, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 4960 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 3480 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 3888, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 3583 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 3888 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 5336, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 5773 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 5336 AND cc2.colonia_id = cc.colonia_id);
INSERT INTO calles_colonias (calle_id, colonia_id, activo) SELECT 5765, cc.colonia_id, cc.activo FROM calles_colonias cc WHERE cc.calle_id = 5762 AND cc.eliminado_por IS NULL AND NOT EXISTS (SELECT 1 FROM calles_colonias cc2 WHERE cc2.calle_id = 5765 AND cc2.colonia_id = cc.colonia_id);

-- ============================================
-- 3) DESACTIVAR calles duplicadas ya fusionadas (89)
-- ============================================
UPDATE calles SET activo = 0 WHERE id IN (308, 807, 344, 345, 348, 355, 357, 373, 410, 451, 466, 1458, 565, 606, 613, 616, 636, 670, 703, 742, 743, 774, 778, 1882, 817, 827, 2653, 945, 966, 967, 1005, 1050, 1103, 1058, 1059, 1094, 1114, 1117, 1157, 1145, 2564, 1197, 1198, 1217, 5647, 1356, 1358, 1400, 1440, 1441, 1457, 1459, 1482, 1495, 1588, 1597, 1599, 1600, 1638, 1650, 1762, 1857, 1997, 2001, 2020, 2060, 3460, 2592, 2267, 2221, 2240, 2338, 2581, 2621, 4936, 2688, 2723, 2994, 3041, 3076, 5779, 3364, 3365, 3366, 3459, 4960, 3583, 5773, 5762);

-- ============================================
-- 4) DESACTIVAR relaciones calles_colonias de las calles fusionadas
-- ============================================
UPDATE calles_colonias SET activo = 0 WHERE calle_id IN (308, 807, 344, 345, 348, 355, 357, 373, 410, 451, 466, 1458, 565, 606, 613, 616, 636, 670, 703, 742, 743, 774, 778, 1882, 817, 827, 2653, 945, 966, 967, 1005, 1050, 1103, 1058, 1059, 1094, 1114, 1117, 1157, 1145, 2564, 1197, 1198, 1217, 5647, 1356, 1358, 1400, 1440, 1441, 1457, 1459, 1482, 1495, 1588, 1597, 1599, 1600, 1638, 1650, 1762, 1857, 1997, 2001, 2020, 2060, 3460, 2592, 2267, 2221, 2240, 2338, 2581, 2621, 4936, 2688, 2723, 2994, 3041, 3076, 5779, 3364, 3365, 3366, 3459, 4960, 3583, 5773, 5762);

COMMIT;
