-- data_008_colonias_sepomex_tepic_xalisco.sql
-- Fuente: Catalogo Nacional de Codigos Postales (SEPOMEX / Correos de Mexico) - archivo Nayarit
-- Alcance: SOLO Tepic y Xalisco (Puerto Vallarta y Bahia de Banderas quedan pendientes)
-- Generado 2026-08-23T23:21:13.982Z

START TRANSACTION;

-- ============================================
-- 0) FIX: nombre_normalizado mal calculado en datos existentes (29 colonias, Tepic/Xalisco)
--    Bug: nombre_normalizado = copia literal de nombre, sin lower/sin quitar acentos
-- ============================================
UPDATE calles SET nombre = 'Av. Francisco Villa', nombre_normalizado = 'av. francisco villa' WHERE id = 1;
UPDATE colonias SET nombre = 'San Juan', nombre_normalizado = 'san juan' WHERE id = 2;
UPDATE colonias SET nombre = 'Rincón de San Juan', nombre_normalizado = 'rincon de san juan' WHERE id = 3;
UPDATE colonias SET nombre = 'Valle de Matatipac', nombre_normalizado = 'valle de matatipac' WHERE id = 4;
UPDATE colonias SET nombre = 'Versalles', nombre_normalizado = 'versalles' WHERE id = 5;
UPDATE colonias SET nombre = 'Versalles Sur', nombre_normalizado = 'versalles sur' WHERE id = 6;
UPDATE colonias SET nombre = '20 de Noviembre', nombre_normalizado = '20 de noviembre' WHERE id = 7;
UPDATE colonias SET nombre = '2 de Agosto', nombre_normalizado = '2 de agosto' WHERE id = 8;
UPDATE colonias SET nombre = '12 de Diciembre', nombre_normalizado = '12 de diciembre' WHERE id = 9;
UPDATE colonias SET nombre = 'Los Llanitos', nombre_normalizado = 'los llanitos' WHERE id = 10;
UPDATE colonias SET nombre = '18 de Agosto', nombre_normalizado = '18 de agosto' WHERE id = 11;
UPDATE colonias SET nombre = 'Villas del Nayar', nombre_normalizado = 'villas del nayar' WHERE id = 12;
UPDATE colonias SET nombre = 'Ciudad Industrial', nombre_normalizado = 'ciudad industrial' WHERE id = 13;
UPDATE colonias SET nombre = 'Jazmines', nombre_normalizado = 'jazmines' WHERE id = 14;
UPDATE colonias SET nombre = 'Puerta de la Cantera', nombre_normalizado = 'puerta de la cantera' WHERE id = 15;
UPDATE colonias SET nombre = 'Villas del Molino', nombre_normalizado = 'villas del molino' WHERE id = 16;
UPDATE colonias SET nombre = 'Villas del Parque', nombre_normalizado = 'villas del parque' WHERE id = 17;
UPDATE colonias SET nombre = 'Villas del Prado', nombre_normalizado = 'villas del prado' WHERE id = 18;
UPDATE colonias SET nombre = 'Villas del Roble', nombre_normalizado = 'villas del roble' WHERE id = 19;
UPDATE colonias SET nombre = 'Vistas de la Cantera', nombre_normalizado = 'vistas de la cantera' WHERE id = 20;
UPDATE colonias SET nombre = 'Aramara', nombre_normalizado = 'aramara' WHERE id = 21;
UPDATE colonias SET nombre = 'La Floresta', nombre_normalizado = 'la floresta' WHERE id = 22;
UPDATE colonias SET nombre = 'Olimpo', nombre_normalizado = 'olimpo' WHERE id = 23;
UPDATE colonias SET nombre = 'Cantera del Nayar', nombre_normalizado = 'cantera del nayar' WHERE id = 24;
UPDATE colonias SET nombre = 'Los Agaves', nombre_normalizado = 'los agaves' WHERE id = 25;
UPDATE colonias SET nombre = 'Aviación', nombre_normalizado = 'aviacion' WHERE id = 26;
UPDATE colonias SET nombre = '15 de Mayo', nombre_normalizado = '15 de mayo' WHERE id = 27;
UPDATE colonias SET nombre = 'Villas de la Paz', nombre_normalizado = 'villas de la paz' WHERE id = 28;
UPDATE colonias SET nombre = 'El Rodeo', nombre_normalizado = 'el rodeo' WHERE id = 37;
UPDATE colonias SET nombre = 'Ciudad Industrial', nombre_normalizado = 'ciudad industrial' WHERE id = 38;

-- ============================================
-- 1) CODIGOS POSTALES FALTANTES (59)
-- ============================================
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63018', 'Colonia', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63058', 'Colonia', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63059', 'Colonia', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63061', 'Colonia', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63062', 'Colonia', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63066', 'Colonia', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63067', 'Colonia', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63068', 'Colonia', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63069', 'Colonia', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63081', 'Colonia', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63082', 'Colonia', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63083', 'Colonia', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63084', 'Colonia', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63088', 'Colonia', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63089', 'Colonia', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63109', 'Fraccionamiento', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63114', 'Colonia', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63115', 'Fraccionamiento', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63116', 'Unidad habitacional', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63119', 'Unidad habitacional', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63120', 'Colonia', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63128', 'Colonia', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63150', 'Colonia', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63163', 'Colonia', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63164', 'Colonia', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63165', 'Fraccionamiento', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63166', 'Colonia', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63167', 'Colonia', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63168', 'Fraccionamiento', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63169', 'Fraccionamiento', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63186', 'Fraccionamiento', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63193', 'Colonia', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63194', 'Colonia', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63500', 'Colonia', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63501', 'Pueblo', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63502', 'Ejido', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63503', 'Ejido', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63504', 'Ejido', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63505', 'Ejido', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63506', 'Fraccionamiento', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63507', 'Ranchería', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63508', 'Ejido', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63509', 'Ranchería', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63510', 'Ranchería', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63511', 'Colonia', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63512', 'Ranchería', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63513', 'Ranchería', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63514', 'Ejido', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63515', 'Ejido', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63517', 'Ranchería', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63519', 'Ranchería', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63522', 'Ranchería', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63523', 'Ranchería', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63524', 'Ranchería', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63526', 'Ejido', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63527', 'Pueblo', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63528', 'Ejido', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (1, '63529', 'Ejido', 1);
INSERT INTO codigos_postales (ciudad_id, codigo_postal, tipo_asentamiento_principal, activo) VALUES (2, '63799', 'Aeropuerto', 1);

-- ============================================
-- 2) COLONIAS FALTANTES (419)
-- ============================================
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (1, 'Tepic Centro', 'tepic centro', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (1, 'Esteban Baca Calderón', 'esteban baca calderon', 'Unidad habitacional', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (2, 'Amado Nervo', 'amado nervo', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (2, 'Paseo de La Constitución', 'paseo de la constitucion', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (2, 'Sacristán', 'sacristan', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63018'), 'El Punto', 'el punto', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63018'), 'Jesús Salas', 'jesus salas', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (58, 'Francisco Villa', 'francisco villa', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (58, 'Loma Hermosa', 'loma hermosa', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (3, 'Santa Teresita', 'santa teresita', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (3, 'Unidad Deportiva Santa Teresita', 'unidad deportiva santa teresita', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (61, 'Ojo de Agua', 'ojo de agua', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (61, 'Senderos del Monte', 'senderos del monte', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (61, 'Buenos Aires', 'buenos aires', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (4, 'Cuitlahuac', 'cuitlahuac', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (4, 'Chapultepec', 'chapultepec', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (4, 'Lomas de La Cruz Sutse', 'lomas de la cruz sutse', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (4, 'San José', 'san jose', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (62, 'Jardines del Valle', 'jardines del valle', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (62, 'Villas del Paraíso', 'villas del paraiso', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (62, 'Bugambilias', 'bugambilias', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (62, 'Jardines del Paraíso', 'jardines del paraiso', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (62, 'Tulipanes', 'tulipanes', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (62, 'Valle de La Cruz', 'valle de la cruz', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (62, 'Valle de Zaragoza', 'valle de zaragoza', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (62, 'Ampliación El Paraíso', 'ampliacion el paraiso', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (62, 'Nuevo Progreso', 'nuevo progreso', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (62, 'Islas del Paraíso', 'islas del paraiso', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (64, 'Lomas de La Cruz', 'lomas de la cruz', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (64, 'Los Viveros', 'los viveros', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (64, 'Sindicalistas', 'sindicalistas', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (64, 'Villas de la Cruz', 'villas de la cruz', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (64, 'Residencial La Esmeralda', 'residencial la esmeralda', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (64, 'Villas de Aztlan', 'villas de aztlan', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (64, 'Valle Verde Conalep', 'valle verde conalep', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (64, 'Ingeniero Agrónomo', 'ingeniero agronomo', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (64, 'La Loma', 'la loma', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (64, 'Los Arcos', 'los arcos', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (64, 'La Lomita', 'la lomita', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (64, 'Villas de Zapopan', 'villas de zapopan', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (64, 'Villas de la Laguna', 'villas de la laguna', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (64, 'Villas Arana', 'villas arana', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (65, 'El Mirador INFONAVIT', 'el mirador infonavit', 'Unidad habitacional', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (65, 'El Paraíso', 'el paraiso', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (65, 'Emilio M. González', 'emilio m. gonzalez', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (65, 'Las Conchas', 'las conchas', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (65, 'Las Pares', 'las pares', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (65, 'Rancho las Cruces', 'rancho las cruces', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (66, 'Puerta de La Laguna', 'puerta de la laguna', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (66, 'Real Montecarlo', 'real montecarlo', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (66, 'Camino Real', 'camino real', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (66, 'Cuba', 'cuba', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (66, 'Aztlán El Verde', 'aztlan el verde', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (66, 'Riveras de La Laguna', 'riveras de la laguna', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (6, 'El Parían', 'el parian', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (6, 'Miguel Ángel Paredes', 'miguel angel paredes', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63058'), 'Rivas Allende', 'rivas allende', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63058'), 'Sandino', 'sandino', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63058'), 'Sánchez Ibarra', 'sanchez ibarra', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63059'), 'Lomas de Cortez', 'lomas de cortez', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63059'), 'Lomas de La Laguna', 'lomas de la laguna', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63059'), 'Villas de Matatipac', 'villas de matatipac', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63059'), 'El Limón', 'el limon', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63059'), 'San Juanito', 'san juanito', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63061'), 'Lomas Altas', 'lomas altas', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63062'), 'El Palomar', 'el palomar', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63062'), 'Lomas Bonitas', 'lomas bonitas', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63062'), 'Alaska', 'alaska', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63062'), 'Rinconada Residencial', 'rinconada residencial', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63066'), 'Lomas del Valle', 'lomas del valle', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63066'), 'Florencia', 'florencia', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63067'), 'Las Flores', 'las flores', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63068'), 'Luis Echeverría A.', 'luis echeverria a.', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63068'), 'América Manríquez', 'america manriquez', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63069'), 'Primero de Mayo', 'primero de mayo', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63069'), 'Unidad Obrera', 'unidad obrera', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (8, 'Emiliano Zapata', 'emiliano zapata', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (8, 'La Huerta', 'la huerta', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (9, 'Heriberto Casas', 'heriberto casas', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63081'), 'Acayapan', 'acayapan', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63082'), 'El Faisán', 'el faisan', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63082'), 'El Naranjal', 'el naranjal', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63083'), 'Ruinas de Jauja', 'ruinas de jauja', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63083'), 'Ampliación Santa Teresita', 'ampliacion santa teresita', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63084'), 'Ingeniero Aguayo', 'ingeniero aguayo', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63084'), 'Los Pinos', 'los pinos', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63088'), 'Santa Fe', 'santa fe', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63089'), 'Santa Cecilia', 'santa cecilia', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63109'), 'Estadios', 'estadios', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (12, 'Lindavista', 'lindavista', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (12, 'Rodeo de La Punta', 'rodeo de la punta', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63114'), 'Nuevas Delicias', 'nuevas delicias', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63114'), 'Solidaridad INFONAVIT', 'solidaridad infonavit', 'Unidad habitacional', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63114'), 'Colinas del Nayar', 'colinas del nayar', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63114'), 'Parque Funeral Jardines de San Juan', 'parque funeral jardines de san juan', 'Equipamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63114'), 'Guadalupe', 'guadalupe', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63114'), 'Solidaridad Primavera', 'solidaridad primavera', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63114'), 'Aztlán Solidaridad', 'aztlan solidaridad', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63114'), 'Ecologistas', 'ecologistas', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63114'), 'Dieciséis de Septiembre', 'dieciseis de septiembre', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63114'), 'Residencial los Olivos', 'residencial los olivos', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63115'), 'SPAUAN', 'spauan', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63115'), 'Lomas de Lindavista', 'lomas de lindavista', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63116'), 'FOVISSSTE 2a Etapa', 'fovissste 2a etapa', 'Unidad habitacional', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (13, 'Brisas de San Juan', 'brisas de san juan', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (13, 'Las Brisas', 'las brisas', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (13, 'Las Brisas FOVISSSTE', 'las brisas fovissste', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63119'), 'FOVISSSTE 1a Etapa', 'fovissste 1a etapa', 'Unidad habitacional', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63120'), 'IMSS', 'imss', 'Unidad habitacional', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63120'), 'Obrera CTM', 'obrera ctm', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63120'), 'Villa San Ángel', 'villa san angel', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63120'), 'San Ángel', 'san angel', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63128'), 'Lomas de San Juan', 'lomas de san juan', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (67, 'Arboledas', 'arboledas', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (67, 'Aves del Paraíso', 'aves del paraiso', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (67, 'Jagüey', 'jaguey', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (67, 'Cora', 'cora', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (67, 'Rey Nayar', 'rey nayar', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (67, 'Tío Baltazar', 'tio baltazar', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (67, 'Leonardo Rodríguez Alcaine', 'leonardo rodriguez alcaine', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (15, 'El Tecolote', 'el tecolote', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (15, 'El Tecolote INFONAVIT', 'el tecolote infonavit', 'Unidad habitacional', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (16, 'Independencia', 'independencia', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (17, 'Residencial La Loma', 'residencial la loma', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63150'), 'Menchaca', 'menchaca', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (20, 'Universidad Autónoma de Nayarit', 'universidad autonoma de nayarit', 'Equipamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (21, 'Burócrata Federal', 'burocrata federal', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (23, 'Caja de Agua', 'caja de agua', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (24, 'San Antonio', 'san antonio', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (25, 'Electricistas', 'electricistas', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (25, 'Morelos', 'morelos', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63163'), 'Corralón', 'corralon', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63164'), 'El Pedregal', 'el pedregal', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63164'), 'Nueva Alemania', 'nueva alemania', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63164'), 'Pedregal de San Juan', 'pedregal de san juan', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63165'), 'Biosfera Residencial', 'biosfera residencial', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63166'), 'Benito Juárez', 'benito juarez', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63166'), 'Del Bosque', 'del bosque', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63167'), 'Peñita', 'penita', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63167'), 'Labores de Godínez', 'labores de godinez', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63168'), 'Jardines de La Cruz', 'jardines de la cruz', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63169'), 'Fray Junipero Serra', 'fray junipero serra', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (26, 'Dr. Lucas Vallarta', 'dr. lucas vallarta', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (26, 'Ferrocarrilero 2a Secc.', 'ferrocarrilero 2a secc.', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (26, 'Las Aves', 'las aves', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (26, 'Lagos de Aztlán', 'lagos de aztlan', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (26, 'México', 'mexico', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (26, 'Flamingos', 'flamingos', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (26, 'Gobierno del Cambio I', 'gobierno del cambio i', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (72, 'Unidos por tu Tranquilidad', 'unidos por tu tranquilidad', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (72, 'Los Álamos', 'los alamos', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (72, '3 de Julio', '3 de julio', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (72, 'Nuevo Amanecer', 'nuevo amanecer', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (72, 'Aurora', 'aurora', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (27, 'Puerta Encanto', 'puerta encanto', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (27, 'Ciudad Industrial Microindustria', 'ciudad industrial microindustria', 'Zona industrial', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (27, 'Jesús García', 'jesus garcia', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (27, 'Nayarabastos', 'nayarabastos', 'Zona comercial', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (27, 'Parque Ecológico', 'parque ecologico', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (27, 'Puerta Jardín', 'puerta jardin', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (27, 'Colinas del Valle', 'colinas del valle', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (27, 'Porta Alta', 'porta alta', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (27, 'Puerta Paraíso', 'puerta paraiso', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (27, 'Lomas del Encanto', 'lomas del encanto', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (27, 'Antonio Echevarría Domínguez', 'antonio echevarria dominguez', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (27, 'Responsabilidad Social Comunitaria', 'responsabilidad social comunitaria', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (27, 'Villas Aramara', 'villas aramara', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (27, 'Real de Lozada', 'real de lozada', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (27, 'Real de la Noria', 'real de la noria', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (27, 'Esteban Baca Calderón', 'esteban baca calderon', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (27, 'SUTSEM 21 de Mayo', 'sutsem 21 de mayo', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (27, 'El Rubí', 'el rubi', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (27, 'Justino Ávila Arce', 'justino avila arce', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (27, 'Jardines del Parque', 'jardines del parque', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (27, 'Villas de La Cantera', 'villas de la cantera', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (27, 'Revolución', 'revolucion', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (27, 'Ejidal', 'ejidal', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (27, 'Molinos del Rey', 'molinos del rey', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (27, 'Del Sol', 'del sol', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (27, 'Puesta del Sol', 'puesta del sol', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (73, 'Prieto Crispín', 'prieto crispin', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (73, 'Cuatro Milpas', 'cuatro milpas', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (73, 'Flores Magón', 'flores magon', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (73, 'Genaro Vázquez', 'genaro vazquez', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (73, 'La Esperanza', 'la esperanza', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (73, 'Venceremos', 'venceremos', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (73, 'Zitácua', 'zitacua', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (73, 'Las Fincas', 'las fincas', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (28, 'Benito Juárez Oriente', 'benito juarez oriente', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (28, 'Comerciantes', 'comerciantes', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (28, 'Dr. Ignacio Cuesta Barrios', 'dr. ignacio cuesta barrios', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (28, 'Gobernadores', 'gobernadores', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (28, 'Instituto Tecnológico de Tepic', 'instituto tecnologico de tepic', 'Equipamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (28, 'Lagos del Country', 'lagos del country', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (28, 'Oriental', 'oriental', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (28, 'Quinta Los Lirios', 'quinta los lirios', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (28, 'Valle del Country', 'valle del country', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (28, 'Luis Donaldo Colosio Murrieta', 'luis donaldo colosio murrieta', 'Unidad habitacional', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (29, 'Cáp. Orozco', 'cap. orozco', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (29, 'Colonial', 'colonial', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (29, 'Gustavo Díaz Ordaz', 'gustavo diaz ordaz', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (30, 'Juventud', 'juventud', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (30, 'El Capomo', 'el capomo', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (30, 'Ferrocarrilero 1a Secc.', 'ferrocarrilero 1a secc.', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (30, 'Heriberto Jara', 'heriberto jara', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (30, 'Simancas', 'simancas', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (30, 'AGEUAN Los Limones', 'ageuan los limones', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (30, 'Los Manantiales', 'los manantiales', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (30, 'Ampliación Tierra y Libertad', 'ampliacion tierra y libertad', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (30, 'Los Colomos', 'los colomos', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (30, 'Lirios', 'lirios', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (30, 'Villa las Rosas', 'villa las rosas', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (31, 'Luis Donaldo Colosio', 'luis donaldo colosio', 'Unidad habitacional', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (31, 'Tierra y Libertad', 'tierra y libertad', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (32, 'Gilberto Flores Muñoz', 'gilberto flores munoz', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (33, 'Burócrata Estatal', 'burocrata estatal', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (33, 'Colinas del Rey', 'colinas del rey', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (33, 'Cuauhtémoc', 'cuauhtemoc', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (33, 'Moctezuma', 'moctezuma', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (33, 'Valle Dorado', 'valle dorado', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (33, 'Valle de Nayarit', 'valle de nayarit', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (33, 'Bethel', 'bethel', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (35, 'Insurgentes', 'insurgentes', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (36, 'Miravalles', 'miravalles', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (37, 'El Ocho', 'el ocho', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (37, 'Félix Peña', 'felix pena', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (37, 'Los Fresnos Poniente', 'los fresnos poniente', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (37, 'Las Cumbres', 'las cumbres', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63186'), 'IMSS', 'imss', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63186'), 'Leyva Medina', 'leyva medina', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63186'), 'San Martín', 'san martin', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (38, 'Juan Escutia', 'juan escutia', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (38, 'Lázaro Cárdenas', 'lazaro cardenas', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (38, 'Los Fresnos Oriente', 'los fresnos oriente', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (38, 'José María Martínez (El Molino)', 'jose maria martinez (el molino)', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63193'), 'Miguel Hidalgo', 'miguel hidalgo', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63194'), 'El Puerto', 'el puerto', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63194'), 'Ladrilleras', 'ladrilleras', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63194'), 'Nuevas Palomas', 'nuevas palomas', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63194'), 'Puente de San Cayetano', 'puente de san cayetano', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63194'), 'Valle Magno', 'valle magno', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63194'), 'Paraíso Residencial', 'paraiso residencial', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63194'), 'El Armadillo', 'el armadillo', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63194'), 'Bonaterra', 'bonaterra', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (39, 'Conasupo', 'conasupo', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (39, 'Extamex', 'extamex', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (39, 'Marco Antonio Fernández', 'marco antonio fernandez', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (39, 'Los Sauces INFONAVIT', 'los sauces infonavit', 'Unidad habitacional', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (39, 'Los Ciruelos', 'los ciruelos', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (39, 'Jacarandas', 'jacarandas', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (39, 'Severiano Ocegueda', 'severiano ocegueda', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (39, 'Las Islas', 'las islas', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (39, 'Las Palomas', 'las palomas', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (39, 'La Joya', 'la joya', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (74, 'Caminera', 'caminera', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (74, 'Castilla', 'castilla', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (74, 'Nueva Aviación', 'nueva aviacion', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (74, 'Periodistas', 'periodistas', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (74, '26 de Septiembre', '26 de septiembre', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (75, '5 de Febrero', '5 de febrero', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (75, 'Hermosa Provincia', 'hermosa provincia', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (75, 'Los Fresnos INFONAVIT', 'los fresnos infonavit', 'Unidad habitacional', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (75, 'Los Sauces', 'los sauces', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (75, 'Unión Popular', 'union popular', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (75, 'Antonio R Laureles', 'antonio r laureles', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (75, 'Plan de Ayala', 'plan de ayala', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (75, 'Niños Héroes', 'ninos heroes', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (75, 'Los Fresnos', 'los fresnos', 'Unidad habitacional', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63500'), 'Hebrón', 'hebron', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63500'), 'Los Sabinos', 'los sabinos', 'Ranchería', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63500'), 'Azucareros', 'azucareros', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63500'), 'Francisco I. Madero (Puga) Centro', 'francisco i. madero (puga) centro', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63500'), 'Francisco Velázquez', 'francisco velazquez', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63500'), 'Lázaro Cárdenas', 'lazaro cardenas', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63500'), 'El Campo', 'el campo', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63500'), '18 de Marzo', '18 de marzo', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63500'), 'El Chorro', 'el chorro', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63500'), 'Caja de Agua', 'caja de agua', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63500'), 'Nueva Valey', 'nueva valey', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63500'), 'Las Parejas', 'las parejas', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63500'), 'Las Cruces', 'las cruces', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63500'), 'El Cerro', 'el cerro', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63501'), 'Bellavista', 'bellavista', 'Pueblo', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63502'), 'El Rincón', 'el rincon', 'Ejido', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63502'), 'San Andrés', 'san andres', 'Pueblo', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63502'), 'La Escondida', 'la escondida', 'Ejido', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63502'), 'La Herradura', 'la herradura', 'Ejido', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63502'), 'El Colorado', 'el colorado', 'Ranchería', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63502'), 'CEFERESO', 'cefereso', 'Equipamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63503'), 'San Fernando', 'san fernando', 'Ejido', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63504'), 'Mora', 'mora', 'Ejido', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63504'), 'Seis de Enero', 'seis de enero', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63505'), 'La Fortuna', 'la fortuna', 'Ejido', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63505'), 'El Pichón', 'el pichon', 'Ranchería', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63505'), 'Lo de Lamedo', 'lo de lamedo', 'Ejido', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63506'), 'San Antonio de Mora', 'san antonio de mora', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63506'), 'Che Guevara', 'che guevara', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63506'), 'La Cantera', 'la cantera', 'Ejido', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63507'), 'Huachines', 'huachines', 'Ranchería', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63507'), 'El Izote', 'el izote', 'Ranchería', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63507'), 'El Ahuacate', 'el ahuacate', 'Ejido', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63507'), 'Las Delicias', 'las delicias', 'Ranchería', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63507'), 'Platanitos', 'platanitos', 'Ranchería', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63507'), 'Venustiano Carranza', 'venustiano carranza', 'Ejido', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63507'), 'Morelos I', 'morelos i', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63508'), 'Camichín de Jauja', 'camichin de jauja', 'Ejido', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63509'), 'El Refugio', 'el refugio', 'Ranchería', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63510'), 'Catorce de Marzo', 'catorce de marzo', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63510'), 'Cinco de Mayo (El Ciruelo)', 'cinco de mayo (el ciruelo)', 'Ranchería', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63510'), 'El Jicote', 'el jicote', 'Ranchería', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63511'), 'Novillero', 'novillero', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63511'), 'Las Joyas', 'las joyas', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63511'), 'La Guadalupana', 'la guadalupana', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63511'), 'Diamante', 'diamante', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63511'), 'El Verde', 'el verde', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63511'), 'San Cayetano', 'san cayetano', 'Ejido', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63511'), 'Volcanes', 'volcanes', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63511'), 'La Corregidora', 'la corregidora', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63512'), 'Las Peñitas (La Repisa)', 'las penitas (la repisa)', 'Ranchería', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63512'), 'Lo de García', 'lo de garcia', 'Ranchería', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63513'), 'Roseta (La Tristeza)', 'roseta (la tristeza)', 'Ranchería', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63514'), 'Las Pilas (El Tepeguaje)', 'las pilas (el tepeguaje)', 'Ejido', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63514'), 'Los Salazares', 'los salazares', 'Ejido', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63515'), 'Benito Juárez (Las Chivas)', 'benito juarez (las chivas)', 'Ejido', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63515'), 'El Espino', 'el espino', 'Ejido', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63515'), 'Jumatán', 'jumatan', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63515'), 'Pajuelazo (El Guanacaste)', 'pajuelazo (el guanacaste)', 'Ejido', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63515'), 'La Resolana', 'la resolana', 'Ranchería', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63517'), 'El Limón', 'el limon', 'Ranchería', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63517'), 'Barranca Blanca', 'barranca blanca', 'Ranchería', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63517'), 'El Trapichillo', 'el trapichillo', 'Ejido', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63519'), 'La Yerba', 'la yerba', 'Ranchería', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63522'), 'Jesús María Cortés', 'jesus maria cortes', 'Ranchería', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63523'), 'Las Norias del Manantial', 'las norias del manantial', 'Ranchería', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63523'), 'Atonalisco', 'atonalisco', 'Ranchería', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63524'), 'El Floreño (El Capulín)', 'el floreno (el capulin)', 'Ranchería', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63524'), 'Santiago de Pochotitán', 'santiago de pochotitan', 'Pueblo', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63524'), 'Buenos Aires', 'buenos aires', 'Rancho', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63524'), 'Caleras de Cofrados', 'caleras de cofrados', 'Ranchería', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63526'), 'Zapote de Picachos', 'zapote de picachos', 'Ejido', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63527'), 'San Luis de Lozada', 'san luis de lozada', 'Pueblo', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63528'), 'Mesa de Picachos (El Casco)', 'mesa de picachos (el casco)', 'Ejido', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 1 AND codigo_postal = '63529'), 'Las Blancas (Carretones de Cerritos)', 'las blancas (carretones de cerritos)', 'Ejido', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (40, 'Lomas Xalisco', 'lomas xalisco', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (40, 'Xalisco Centro', 'xalisco centro', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (40, 'Canoas', 'canoas', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (41, 'Alborada', 'alborada', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (41, 'Salvador Sánchez Vázquez', 'salvador sanchez vazquez', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (41, 'Lomas Bonitas', 'lomas bonitas', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (41, 'Nuevo Progreso', 'nuevo progreso', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (41, 'Huertas de Matatipal', 'huertas de matatipal', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (41, 'Ampliación Nuevo Progreso', 'ampliacion nuevo progreso', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (41, 'Lomas del Nayar', 'lomas del nayar', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (41, 'Las Águilas', 'las aguilas', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (42, 'El Guayabo', 'el guayabo', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (42, 'Puerta del Sol', 'puerta del sol', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (42, 'José Santos Godínez', 'jose santos godinez', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (42, '1ro. de Mayo', '1ro. de mayo', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (42, 'Guadalupe Victoria', 'guadalupe victoria', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (42, 'SUTSEM Landereñas', 'sutsem landerenas', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (42, 'Progreso', 'progreso', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (42, 'Valle de Roma', 'valle de roma', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (43, 'Abel Isiordia', 'abel isiordia', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (43, 'Ramos Millán', 'ramos millan', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (43, 'Jardines de Matatipac', 'jardines de matatipac', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (43, '25 de Abril', '25 de abril', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (43, 'Landereñas', 'landerenas', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (43, 'Los Cordoncillos II', 'los cordoncillos ii', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (43, 'El Navarreño II', 'el navarreno ii', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (43, 'Pueblo Nuevo', 'pueblo nuevo', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (44, 'Puerta Luna', 'puerta luna', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (44, 'Xalisca Residencial Los Laureles', 'xalisca residencial los laureles', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (44, 'Ejidal', 'ejidal', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (44, 'Navarreño', 'navarreno', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (44, 'Hacienda Real', 'hacienda real', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (45, 'Fernando Carrillo', 'fernando carrillo', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (45, 'La Cruz', 'la cruz', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (45, '24 de Febrero', '24 de febrero', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (46, 'Vicente Guerrero', 'vicente guerrero', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (46, 'Nahil', 'nahil', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (46, 'Kiekari', 'kiekari', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (46, 'Las Rosas', 'las rosas', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (46, 'Colinas de San Juan', 'colinas de san juan', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (46, 'Nuevo México', 'nuevo mexico', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (46, 'Real del Bosque', 'real del bosque', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (46, '10 de Mayo', '10 de mayo', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (46, 'Santa Mónica', 'santa monica', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (46, '14 de Febrero', '14 de febrero', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (46, 'Nueva Galicia', 'nueva galicia', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (46, 'José María Morelos', 'jose maria morelos', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (46, 'Villas de Guadalupe', 'villas de guadalupe', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (46, 'Bugambilias', 'bugambilias', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (46, 'Lomas Verdes', 'lomas verdes', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (46, 'Ampliación Xalisco', 'ampliacion xalisco', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (46, 'Tanuz', 'tanuz', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (46, 'El Indio', 'el indio', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (46, 'Las Isabeles', 'las isabeles', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (46, 'Emiliano Zapata', 'emiliano zapata', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (46, 'Colinas de Xalisco', 'colinas de xalisco', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (46, 'Minas de Xalli', 'minas de xalli', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (47, 'Palomas Doradas', 'palomas doradas', 'Fraccionamiento', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (49, 'San Antonio', 'san antonio', 'Ranchería', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (49, 'El Malinal', 'el malinal', 'Ejido', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (51, 'Valles del Nayar', 'valles del nayar', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (51, 'Pantanal', 'pantanal', 'Pueblo', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (52, 'El Carrizal', 'el carrizal', 'Ranchería', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (52, 'Adolfo López Mateos (Las Veredas)', 'adolfo lopez mateos (las veredas)', 'Ranchería', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (52, 'Cofradía de Chocolón', 'cofradia de chocolon', 'Ranchería', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (53, 'Emiliano Zapata (Majadas)', 'emiliano zapata (majadas)', 'Pueblo', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (53, 'Aquiles Serdán', 'aquiles serdan', 'Colonia', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (53, 'Testerazo', 'testerazo', 'Pueblo', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (53, 'San José de Costilla (Estación Costilla)', 'san jose de costilla (estacion costilla)', 'Ejido', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (54, 'Los Fortines', 'los fortines', 'Ranchería', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (54, 'Trigomil', 'trigomil', 'Ejido', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (54, 'La Curva', 'la curva', 'Ejido', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (56, 'El Cuarenteño', 'el cuarenteno', 'Hacienda', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (56, 'Palapita', 'palapita', 'Ranchería', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES (56, 'El Tepozal', 'el tepozal', 'Ejido', 1);
INSERT INTO colonias (codigo_postal_id, nombre, nombre_normalizado, tipo_asentamiento, activo) VALUES ((SELECT id FROM codigos_postales WHERE ciudad_id = 2 AND codigo_postal = '63799'), 'Tepic (Poeta Amado Nervo)', 'tepic (poeta amado nervo)', 'Aeropuerto', 1);

COMMIT;
