CREATE TABLE IF NOT EXISTS search_trend_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  usuario_id INT NULL,
  session_id VARCHAR(80) NULL,
  query_original VARCHAR(500) NOT NULL,
  query_normalizada VARCHAR(500) NULL,
  ciudad VARCHAR(120) NULL,
  categoria_id INT NULL,
  subcategoria_id INT NULL,
  especialidad_id INT NULL,
  categoria_nombre VARCHAR(160) NULL,
  subcategoria_nombre VARCHAR(160) NULL,
  especialidad_nombre VARCHAR(160) NULL,
  intent VARCHAR(80) NULL,
  total_resultados INT NOT NULL DEFAULT 0,
  sin_resultados TINYINT(1) NOT NULL DEFAULT 0,
  lat DECIMAL(10,7) NULL,
  lng DECIMAL(10,7) NULL,
  fecha DATE NOT NULL,
  hora TINYINT UNSIGNED NOT NULL,
  dia_semana TINYINT UNSIGNED NOT NULL,
  creado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_search_trends_fecha_ciudad (fecha, ciudad),
  KEY idx_search_trends_categoria_fecha (categoria_id, fecha),
  KEY idx_search_trends_subcategoria_fecha (subcategoria_id, fecha),
  KEY idx_search_trends_especialidad_fecha (especialidad_id, fecha),
  KEY idx_search_trends_ciudad_categoria_fecha (ciudad, categoria_id, fecha),
  KEY idx_search_trends_hora_fecha (hora, fecha),
  KEY idx_search_trends_query_fecha (query_normalizada(191), fecha)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
