import { SemanticCategory } from '../interfaces/jelpy-semantic.interfaces';

export const JELPY_SEMANTIC_CATEGORIES: SemanticCategory[] = [
  // =========================================================
  // SALUD
  // =========================================================
  {
    clave: 'doctores',
    aliases: [
      'doctor',
      'doctora',
      'doctores',
      'medico',
      'médico',
      'medicos',
      'médicos',
      'consulta medica',
      'consulta médica',
      'doctor general',
      'medico general',
      'médico general',
      'medico cerca',
      'médico cerca',
      'doctor cerca',
      'doctores cerca',
      'consulta medica cerca',
      'consulta médica cerca',
      'medicina general',
      'especialista',
      'especialistas',
      'internista',
      'medico a domicilio',
      'médico a domicilio',
      'doctor a domicilio',
      'atencion medica',
      'atención médica',
      'cita medica',
      'cita médica',
    ],
    categoriaHint: 'Salud',
    subcategoriaHint: 'Doctores',
    servicios: [
      'Médico General',
      'Pediatría',
      'Ginecología',
      'Cardiología',
      'Dermatología',
      'Gastroenterología',
      'Neurología',
      'Traumatología',
      'Urología',
      'Otorrinolaringología',
      'Endocrinología',
      'Alergología',
      'Reumatología',
      'Psiquiatría',
      'Oncología',
      'Medicina del Deporte',
      'Cirugía General',
      'pediatra',
      'ginecologo',
      'ginecólogo',
      'cardiologo',
      'cardiólogo',
      'dermatologo',
      'dermatólogo',
      'traumatologo',
      'traumatólogo',
      'urologo',
      'urólogo',
      'otorrino',
      'endocrino',
      'alergologo',
      'alergólogo',
      'psiquiatra',
      'oncologo',
      'oncólogo',
      'cirujano',
    ],
  },
  {
    clave: 'farmacias',
    aliases: [
      'farmacia',
      'farmacias',
      'medicamentos',
      'medicina',
      'medicinas',
      'botica',
      'boticas',
      'farmasia',
      'farmasi',
      'farmasias',
      'farmacias cerca',
      'medicina de patente',
      'pastillas',
      'medicamento',
      'receta medica',
      'receta médica',
      'farmacia 24 horas',
      'farmacia abierta',
      'farmacia de turno',
      'farmacia de guardia',
      'generico',
      'genérico',
      'genericos',
      'genéricos',
      'donde comprar medicamento',
      'donde comprar medicina',
      'salud farmacia',
    ],
    categoriaHint: 'Salud',
    subcategoriaHint: 'Farmacias',
    servicios: [
      'medicamentos',
      'medicina',
      'medicinas',
      'productos de salud',
      'farmacia abierta',
      'farmacia 24 horas',
    ],
  },
  {
    clave: 'consultorios_medicos',
    aliases: [
      'consultorio',
      'consultorio medico',
      'consultorio médico',
      'consultorios',
      'consultorios medicos',
      'consultorios médicos',
      'consulta',
    ],
    categoriaHint: 'Salud',
    subcategoriaHint: 'Consultorios médicos',
    servicios: [
      'consulta básica',
      'consulta general',
      'consulta medica',
      'consulta médica',
    ],
  },
  {
    clave: 'clinicas',
    aliases: [
      'clinica',
      'clínica',
      'clinicas',
      'clínicas',
      'atencion medica',
      'atención médica',
      'clinica privada',
      'clínica privada',
      'clinica de especialidades',
      'clínica de especialidades',
      'atencion urgente',
      'atención urgente',
      'clinica de salud',
      'centro medico',
      'centro médico',
      'centros medicos',
      'centros médicos',
      'clinica dental',
      'clinica abierta',
      'sanatorio privado',
      'clinica sanatorio',
      'clínica sanatorio',
      'clinica particular',
      'clínica particular',
      'clinica medica',
      'clínica médica',
      'centro de salud',
      'centros de salud',
      'consultorio de urgencias',
      'atencion urgente',
      'atención urgente',
      'urgencias privadas',
      'clinica 24 horas',
      'clínica 24 horas',
    ],
    categoriaHint: 'Salud',
    subcategoriaHint: 'Clínicas',
    servicios: [
      'atención médica',
      'especialidades médicas',
      'consulta médica',
    ],
  },
  {
    clave: 'hospitales',
    aliases: [
      'hospital',
      'hospitales',
      'urgencias',
      'emergencias medicas',
      'emergencias médicas',
      // Términos mexicanos para hospital
      'sanatorio',
      'sanatorios',
      'clinica hospital',
      'clínica hospital',
      'hospital privado',
      'hospital general',
      'hospital civil',
      'nosocomio',
      'centro hospitalario',
      'hospitalizacion',
      'hospitalización',
      'internamiento',
      'sala de urgencias',
      'sala de emergencias',
      'sala de espera',
      'guardia medica',
      'guardia médica',
      'hospital 24 horas',
      'hospital cerca',
      'hospital abierto',
      'necesito hospital',
      'necesito un sanatorio',
      'necesito sanatorio',
    ],
    categoriaHint: 'Salud',
    subcategoriaHint: 'Hospitales',
    servicios: [
      'urgencias',
      'emergencias',
      'hospitalización',
      'atención médica avanzada',
    ],
  },
  {
    clave: 'laboratorios_clinicos',
    aliases: [
      'laboratorio',
      'laboratorios',
      'laboratorio clinico',
      'laboratorio clínico',
      'laboratorios clinicos',
      'laboratorios clínicos',
      'analisis',
      'análisis',
      'estudios clinicos',
      'estudios clínicos',
    ],
    categoriaHint: 'Salud',
    subcategoriaHint: 'Laboratorios clínicos',
    servicios: [
      'análisis clínicos',
      'estudios especializados',
      'estudios de laboratorio',
    ],
  },
  {
    clave: 'opticas',
    aliases: [
      'optica',
      'óptica',
      'opticas',
      'ópticas',
      'lentes',
      'armazones',
      'graduacion',
      'graduación',
      'estudio de la vista',
      'vista',
    ],
    categoriaHint: 'Salud',
    subcategoriaHint: 'Ópticas',
    servicios: [
      'lentes',
      'armazones',
      'estudio de la vista',
      'graduación',
    ],
  },
  {
    clave: 'dentistas',
    aliases: [
      'dentista',
      'dentistas',
      'odontologo',
      'odontólogo',
      'odontologia',
      'odontología',
      'diente',
      'muelas',
      'brackets',
      'ortodoncia',
    ],
    categoriaHint: 'Salud',
    subcategoriaHint: 'Dentistas / Odontología',
    servicios: [
      'ortodoncia',
      'limpieza dental',
      'brackets',
      'muelas',
      'dientes',
    ],
  },
  {
    clave: 'psicologia',
    aliases: [
      'psicologo',
      'psicólogo',
      'psicologa',
      'psicóloga',
      'psicologia',
      'psicología',
      'terapia psicologica',
      'terapia psicológica',
      'sicologo',
      'sicologa',
    ],
    categoriaHint: 'Salud',
    subcategoriaHint: 'Psicología',
    servicios: [
      'terapia',
      'atención psicológica',
      'psicoterapia',
      'salud mental',
    ],
  },
  {
    clave: 'nutricion',
    aliases: [
      'nutriologo',
      'nutriólogo',
      'nutriologa',
      'nutrióloga',
      'nutricion',
      'nutrición',
      'dieta',
      'plan alimenticio',
      'alimentacion saludable',
      'alimentación saludable',
    ],
    categoriaHint: 'Salud',
    subcategoriaHint: 'Nutrición',
    servicios: [
      'planes alimenticios',
      'consulta nutricional',
      'dieta',
      'bajar de peso',
      'alimentación',
    ],
  },
  {
    clave: 'fisioterapia',
    aliases: [
      'fisioterapia',
      'rehabilitacion',
      'rehabilitación',
      'fisio',
      'terapia fisica',
      'terapia física',
      'rehab',
    ],
    categoriaHint: 'Salud',
    subcategoriaHint: 'Fisioterapia / Rehabilitación',
    servicios: [
      'rehabilitación',
      'terapia física',
      'recuperación',
      'lesiones',
    ],
  },
  {
    clave: 'ambulancias',
    aliases: [
      'ambulancia',
      'ambulancias',
      'ambulansia',
      'emergencia',
      'traslado medico',
      'traslado médico',
    ],
    categoriaHint: 'Salud',
    subcategoriaHint: 'Ambulancias',
    servicios: [
      'urgencias móviles',
      'traslado médico',
      'emergencia',
    ],
  },

  // =========================================================
  // COMIDA Y RESTAURANTES
  // =========================================================
  {
    clave: 'taquerias',
    aliases: [
      // Base
      'tacos', 'taco', 'takos', 'tako',
      'taqueria', 'taquería', 'taquerias', 'taquerías',
      'taqueria cerca', 'tacos cerca', 'tacos baratos',
      // Tipos de taco
      'pastor', 'al pastor', 'tacos al pastor',
      'asada', 'carne asada', 'tacos de asada', 'tacos de carne asada',
      'suadero', 'tacos de suadero',
      'birria', 'tacos de birria', 'birrieria', 'birrería',
      'carnitas', 'tacos de carnitas',
      'canasta', 'tacos de canasta',
      'barbacoa', 'tacos de barbacoa',
      'cabeza', 'tacos de cabeza',
      'adobada', 'tacos de adobada',
      // Platillos acompañantes
      'tortas', 'torta', 'torteria', 'tortería',
      'burritos', 'burrito',
      'quesadillas', 'quesadilla',
      'volcanes', 'volcan',
      'sopes', 'sope', 'gorditas', 'gordita',
      'flautas', 'flauta', 'tacos dorados',
      'huaraches', 'huarache',
      'antojitos', 'antojitos mexicanos',
      // Búsquedas coloquiales
      'donde comer tacos', 'taqueria abierta',
      'tacos a domicilio', 'tacos de madrugada',
    ],
    categoriaHint: 'Comida y Restaurantes',
    subcategoriaHint: 'Taquerías',
    servicios: [
      'Tacos al pastor', 'Tacos de asada', 'Tacos de suadero',
      'Tacos de birria', 'Tacos dorados', 'Carnitas',
      'Tortas mexicanas', 'Volcanes', 'Quesadillas',
      'Burritos', 'Sopes', 'Gorditas',
    ],
  },
  {
    clave: 'comida_rapida',
    aliases: [
      // Hamburguesas
      'hamburguesa', 'hamburguesas',
      'hamburgesa', 'hamburgesería', 'hamburgueseria', 'hamburgueses',
      'burger', 'burgers', 'burguer', 'burguers',
      'hamburguer', 'hamburger',
      'smash burger', 'smashburger',
      'doble hamburguesa', 'triple hamburguesa',
      // General comida rápida
      'comida rapida', 'comida rápida', 'fast food',
      'comida express',
      // Alitas
      'alitas', 'alita', 'alitas de pollo', 'wings', 'wingsitos',
      'boneless', 'boneles',
      'alitas bbq', 'alitas picantes',
      // Pollos
      'pollo', 'pollo frito', 'polleria', 'pollería',
      'pollo rostizado', 'pollo asado', 'pollo a la leña',
      'pieza de pollo',
      // Otros
      'hot dog', 'hotdog', 'hot dogs', 'hotdogs',
      'papas fritas', 'papas a la francesa',
      'nuggets', 'dedos de pollo',
      'sandwich', 'sanwich', 'sandwiches',
      // Coloquiales
      'donde comer rapido', 'comida barata', 'hamburguesa cerca',
      'alitas a domicilio', 'pollo a domicilio',
    ],
    categoriaHint: 'Comida y Restaurantes',
    subcategoriaHint: 'Comida rápida',
    servicios: [
      'Hamburguesas', 'Alitas de pollo', 'Boneless',
      'Papas fritas', 'Hot dogs', 'Nuggets',
      'Pollo frito', 'Pollo rostizado', 'Pollo asado',
    ],
  },
  {
    clave: 'comida_japonesa',
    aliases: [
      'sushi',
      'ramen',
      'yakimeshi',
      'gohan',
      'tempura',
      'nigiri',
      'sashimi',
      'japonesa',
      'comida japonesa',
      'oriental japonesa',
      'sushi',
    ],
    categoriaHint: 'Comida y Restaurantes',
    subcategoriaHint: 'Comida japonesa',
    servicios: [
      'Sushi',
      'Ramen',
      'Yakimeshi',
      'Tempura',
      'Sashimi',
      'Nigiri',
      'Gohan',
    ],
  },
  {
    clave: 'pizzerias',
    aliases: [
      'pizza',
      'pizzas',
      'pizzeria',
      'pizzería',
      'pizzerias',
      'pizzerías',
      'calzone',
      'pizza pepperoni',
      'pizza hawaiana',
    ],
    categoriaHint: 'Comida y Restaurantes',
    subcategoriaHint: 'Pizzerías',
    servicios: [
      'Pizza pepperoni',
      'Pizza hawaiana',
      'Pizza mexicana',
      'Pizza vegetariana',
      'Pizza de carnes frías',
      'Calzone',
    ],
  },
  {
    clave: 'mariscos',
    aliases: [
      // Término base y variantes fonéticas
      'mariscos',
      'marisco',
      'mariskos',
      'marisko',
      'marisquería',
      'marisqueria',
      'marisquerias',
      'marisquerías',
      // Platillos específicos
      'ceviche',
      'cevich',
      'seviche',
      'keviche',
      'aguachile',
      'aguachili',
      'coctel de camaron',
      'coctel de camarón',
      'coctel de mariscos',
      'cocteles de mariscos',
      'coctel de camaron',
      'pescado zarandeado',
      'tostadas de mariscos',
      'tostadas de camaron',
      'tostadas de camarón',
      'camarones',
      'camaron',
      'camarón',
      'ostiones',
      'ostión',
      'almejas',
      'almeja',
      'pulpo',
      'pulpos',
      'langosta',
      'langostas',
      'atun',
      'atún',
      'pescado',
      'pescados',
      'peskado',
      // Frases de búsqueda comunes
      'frutos del mar',
      'comida de mar',
      'mariscos frescos',
      'marisqueria cerca',
      'donde comer mariscos',
      'restaurante de mariscos',
      'restaurante mariscos',
    ],
    categoriaHint: 'Comida y Restaurantes',
    subcategoriaHint: 'Mariscos',
    servicios: [
      'Ceviche',
      'Aguachile',
      'Tostadas de mariscos',
      'Coctel de camarón',
      'Pescado zarandeado',
      'Camarones al ajillo',
      'Ostiones',
      'Pulpo',
      'Langosta',
    ],
  },
  {
    clave: 'cafeterias',
    aliases: [
      'cafeteria',
      'cafetería',
      'cafeterias',
      'cafeterías',
      'cafe',
      'café',
      'latte',
      'frappe',
      'frappé',
      'croissants',
      'reposteria',
      'repostería',
      'coffee',
      'espresso',
      'cappuccino',
      'capuchino',
      'americano',
      'matcha',
      'te',
      'té',
      'té de hierbas',
      'infusiones',
      'pan dulce',
      'pan',
      'pastelería',
      'pasteleria',
      'bagel',
      'waffle',
      'waffles',
      'desayuno cafe',
      'brunch',
      'cafecito',
      'cafe de olla',
      'café de olla',
      'mocha',
      'chai',
      'moka',
    ],
    categoriaHint: 'Comida y Restaurantes',
    subcategoriaHint: 'Cafeterías',
    servicios: [
      'Café americano',
      'Café latte',
      'Café frappé',
      'Repostería',
      'Croissants',
    ],
  },
  {
    clave: 'restaurantes_familiares',
    aliases: [
      'restaurante familiar',
      'restaurantes familiares',
      'comida corrida',
      'cocina casera',
      'fonda',
      'fondita',
      'menu del dia',
      'menú del día',
      'restaurante',
      'restaurantes',
      'comer',
      'donde comer',
      'lunch',
      'almuerzo',
      'comedor',
      'comedores',
      'pozole',
      'menudo',
      'caldo de res',
      'caldo tlalpeño',
      'cocido',
      'caldos',
      'sopas',
      'caldo',
      'birria de res',
      'birria en caldillo',
      'mole',
      'enchiladas',
      'tamales',
      'tamales de elote',
      'comida mexicana',
      'cocina mexicana',
      'sabor casero',
    ],
    categoriaHint: 'Comida y Restaurantes',
    subcategoriaHint: 'Restaurantes familiares',
    servicios: [
      'Comida corrida',
      'Cocina casera',
      'Menú del día',
    ],
  },
  {
    clave: 'postres_helados',
    aliases: [
      'postres',
      'helados',
      'helado',
      'nieves',
      'crepas',
      'pasteles',
      'reposteria',
      'repostería',
      // Coloquial mexicano
      'raspado',
      'raspados',
      'raspadora',
      'nieve de garrafa',
      'nieves de garrafa',
      'nieve artesanal',
      'paleta',
      'paletas',
      'paletas de hielo',
      'paleta de hielo',
      'paleta helada',
      'chamoyada',
      'mangonada',
      'mango con chile',
      'frío frío',
      'esquimo',
      'esquimales',
      'mini mel',
      'paleta de agua',
      'paleta de leche',
      'donde hay nieves',
      'donde venden raspados',
      'nieveria',
      'nevería',
      'heladeria',
      'heladería',
    ],
    categoriaHint: 'Comida y Restaurantes',
    subcategoriaHint: 'Postres y Helados',
    servicios: [
      'Helados',
      'Nieves',
      'Crepas',
      'Pasteles',
    ],
  },
  {
    clave: 'parrilladas',
    aliases: [
      'parrilla',
      'parrilladas',
      'asador',
      'asadores',
      'bbq',
      'brisket',
      'costillas',
      'cortes de carne',
      'carnes asadas',
      'arrachera',
    ],
    categoriaHint: 'Comida y Restaurantes',
    subcategoriaHint: 'Parrilladas y Asadores',
    servicios: [
      'Cortes de carne',
      'BBQ',
      'Hamburguesas parrilleras',
      'brisket',
      'costillas',
    ],
  },
  {
    clave: 'comida_italiana',
    aliases: [
      'italiana',
      'comida italiana',
      'pasta',
      'pastas',
      'lasaña',
      'lasaña',
      'panini',
      'pizza artesanal',
    ],
    categoriaHint: 'Comida y Restaurantes',
    subcategoriaHint: 'Comida italiana',
    servicios: [
      'Pasta',
      'Pizza artesanal',
      'Panini',
    ],
  },
  {
    clave: 'comida_china',
    aliases: [
      'china',
      'comida china',
      'arroz frito',
      'pollo agridulce',
      'rollos primavera',
      'oriental',
    ],
    categoriaHint: 'Comida y Restaurantes',
    subcategoriaHint: 'Comida china',
    servicios: [
      'Arroz frito',
      'Pollo agridulce',
      'Rollos primavera',
    ],
  },
  {
    clave: 'comida_mexicana',
    aliases: [
      'mexicana',
      'comida mexicana',
      'pozole',
      'enchiladas',
      'birria',
      'antojitos',
      'comida tradicional',
    ],
    categoriaHint: 'Comida y Restaurantes',
    subcategoriaHint: 'Comida mexicana',
    servicios: [
      'Pozole',
      'Enchiladas',
      'Birria',
    ],
  },
  {
    clave: 'food_trucks',
    aliases: [
      'food truck',
      'food trucks',
      'comida movil',
      'comida móvil',
      'camion de comida',
      'camión de comida',
    ],
    categoriaHint: 'Comida y Restaurantes',
    subcategoriaHint: 'Food Trucks',
    servicios: [
      'Snacks',
      'Hamburguesas food truck',
      'Bebidas frías',
    ],
  },
  {
    clave: 'antojitos',
    aliases: [
      'antojitos',
      'antojitos mexicanos',
      'elotes',
      'elote',
      'elote asado',
      'elote cocido',
      'esquites',
      'esquite',
      'churros',
      'churro',
      'botanas',
      'snacks callejeros',
      // Antojitos coloquiales mexicanos
      'garnachas',
      'garnacha',
      'tlacoyo',
      'tlacoyos',
      'memela',
      'memelas',
      'tetela',
      'tetelas',
      'gordas',
      'gorda',
      'tostadas',
      'tostada',
      'sopes callejeros',
      'atole',
      'champurrado',
      'tamale',
      'tamales de olla',
      'tamal',
      'elotes locos',
      'dorilocos',
      'tostilocos',
      'preparadas',
      'botana preparada',
      'cacahuates',
      'pepitas',
      'cacahuate japonés',
      'colaciones',
      'mango enchilado',
      'fruta con chile',
    ],
    categoriaHint: 'Comida y Restaurantes',
    subcategoriaHint: 'Antojitos',
    servicios: [
      'Elotes',
      'Esquites',
      'Churros',
    ],
  },
  {
    clave: 'comida_saludable',
    aliases: [
      'comida saludable',
      'saludable',
      'ensaladas',
      'bowls',
      'jugos naturales',
      'smoothies',
      'fit',
    ],
    categoriaHint: 'Comida y Restaurantes',
    subcategoriaHint: 'Comida saludable',
    servicios: [
      'Ensaladas',
      'Bowls',
      'Jugos naturales',
    ],
  },
  {
    clave: 'bares_cantinas_comida',
    aliases: [
      'bar',
      'bares',
      'cantina',
      'cantinas',
      'bar cantina',
      'bar deportivo',
      'bar karaoke',
      'bar lounge',
      'bar con terraza',
      'cerveza artesanal',
      'mixologia',
      'mixología',
      // Coloquial mexicano de bebidas
      'cheve',
      'chevas',
      'caguama',
      'caguamas',
      'caguameria',
      'caguamería',
      'michelada',
      'micheladas',
      'chelada',
      'cheladas',
      'cerveza fría',
      'cerveza helada',
      'donde tomar una cheve',
      'donde hay caguamas',
      'pulquería',
      'pulqueria',
      'pulque',
      'mezcal',
      'mezcaleria',
      'mezcalería',
      'tequila',
      'cantina con botanas',
      'cerveceria',
      'cervecería',
      'botanas y chupes',
    ],
    categoriaHint: 'Comida y Restaurantes',
    subcategoriaHint: 'Bares y Cantinas',
    servicios: [
      'Mixología',
      'Bar Cantina',
      'Bar Deportivo',
      'Bar de Música en vivo',
      'Bar Karaoke',
      'Bar Lounge',
      'Bar con terraza',
      'Cantina',
      'Cerveza artesanal',
      'Botanas',
    ],
  },
  {
    clave: 'panaderias',
    aliases: [
      'panaderia',
      'panadería',
      'panaderias',
      'panaderías',
      'pan dulce',
      'pan artesanal',
      'baguettes',
      'pan',
      // Tipos de pan mexicano
      'concha',
      'conchas',
      'cuernito',
      'cuernitos',
      'polvoron',
      'polvorón',
      'polvorones',
      'mantecada',
      'mantecadas',
      'donas',
      'dona',
      'donut',
      'donuts',
      'empanada',
      'empanadas',
      'pan de elote',
      'pan de muerto',
      'rosca',
      'rosca de reyes',
      'telera',
      'teleras',
      'bolillo',
      'bolillos',
      'baguette',
      'pan integral',
      'donde venden pan',
      'donde hay pan dulce',
      'panadero',
    ],
    categoriaHint: 'Comida y Restaurantes',
    subcategoriaHint: 'Panaderías',
    servicios: [
      'Pan dulce',
      'Pan artesanal',
      'Baguettes',
    ],
  },

  // =========================================================
  // AUTOMOTRIZ
  // =========================================================
  {
    clave: 'mecanicos',
    aliases: [
      'mecanico',
      'mecánico',
      'mecanicos',
      'mecánicos',
      'mecaniko',
      'taller mecanico',
      'taller mecánico',
      'mecanico automotriz',
      'mecánico automotriz',
      'carro descompuesto',
      'auto descompuesto',
    ],
    categoriaHint: 'Automotriz',
    subcategoriaHint: 'Mecánicos',
    servicios: [
      'Mecánico general',
      'Mecánico diesel',
      'Mecánico de frenos',
      'Mecánico de suspensión',
      'Mecánico de transmisión',
      'Mecánico de clutch',
      'frenos',
      'clutch',
      'transmision',
      'transmisión',
      'suspension',
      'suspensión',
      'diesel',
    ],
  },
  {
    clave: 'taller_mecanico',
    aliases: [
      'taller',
      'taller mecanico',
      'taller mecánico',
      'reparacion de motor',
      'reparación de motor',
      'afinacion',
      'afinación',
      'mantenimiento automotriz',
      'bandas',
      'radiador',
    ],
    categoriaHint: 'Automotriz',
    subcategoriaHint: 'Taller mecánico',
    servicios: [
      'Reparación de motor',
      'Afinación automotriz',
      'Servicio de mantenimiento automotriz',
      'Reparación de sistema de enfriamiento',
      'Cambio de bandas automotrices',
    ],
  },
  {
    clave: 'llanteras',
    aliases: [
      'llantera',
      'llanteras',
      'llantas',
      'ponchadura',
      'ponchado',
      'parchar llanta',
      'parche de llanta',
      'rin',
      'rines',
    ],
    categoriaHint: 'Automotriz',
    subcategoriaHint: 'Llanteras',
    servicios: [
      'Venta de llantas nuevas',
      'Reparación de llantas',
      'Balanceo de ruedas',
      'Montaje de llantas',
      'Venta de rines',
      'balanceo',
      'llanta nueva',
    ],
  },
  {
    clave: 'llantera_movil',
    aliases: [
      'llantera movil',
      'llantera móvil',
      'llantas a domicilio',
      'auxilio de llantas',
      'ponchadura a domicilio',
      'cambio de llanta a domicilio',
      'inflado de llantas',
    ],
    categoriaHint: 'Automotriz',
    subcategoriaHint: 'Llantera móvil',
    servicios: [
      'Cambio de llantas a domicilio',
      'Reparación de llantas a domicilio',
      'Auxilio vial por ponchadura',
      'Inflado de llantas a domicilio',
    ],
  },
  {
    clave: 'electrico_automotriz',
    aliases: [
      'electrico automotriz',
      'eléctrico automotriz',
      'electrico de carro',
      'eléctrico de carro',
      'alternador',
      'marcha',
      'luces automotrices',
      'falla electrica carro',
      'falla eléctrica carro',
    ],
    categoriaHint: 'Automotriz',
    subcategoriaHint: 'Eléctrico automotriz',
    servicios: [
      'Reparación de sistema eléctrico automotriz',
      'Reparación de alternador',
      'Reparación de marcha',
      'Instalación de luces automotrices',
      'Diagnóstico eléctrico computarizado',
    ],
  },
  {
    clave: 'refaccionarias',
    aliases: [
      'refaccionaria',
      'refaccionarias',
      'autopartes',
      'refacciones',
      'baterias',
      'baterías',
      'filtros',
      'aceites',
      'accesorios para auto',
    ],
    categoriaHint: 'Automotriz',
    subcategoriaHint: 'Refaccionarias',
    servicios: [
      'Venta de autopartes',
      'Venta de baterías automotrices',
      'Venta de filtros automotrices',
      'Venta de aceites automotrices',
      'Venta de accesorios automotrices',
    ],
  },
  {
    clave: 'autolavados',
    aliases: [
      'autolavado',
      'autolavados',
      'lavado de autos',
      'lavado de carro',
      'lavado interior',
      'detallado',
      'encerado',
      'pulido',
    ],
    categoriaHint: 'Automotriz',
    subcategoriaHint: 'Autolavados',
    servicios: [
      'Lavado exterior de autos',
      'Lavado interior de autos',
      'Lavado completo de automóvil',
      'Detallado automotriz',
      'Pulido y encerado de autos',
    ],
  },
  {
    clave: 'alineacion_balanceo',
    aliases: [
      'alineacion',
      'alineación',
      'balanceo',
      'alineacion y balanceo',
      'alineación y balanceo',
      'ajuste de suspension',
      'ajuste de suspensión',
    ],
    categoriaHint: 'Automotriz',
    subcategoriaHint: 'Alineación y balanceo',
    servicios: [
      'Alineación automotriz',
      'Balanceo automotriz',
      'Alineación computarizada',
      'Ajuste de suspensión',
    ],
  },
  {
    clave: 'hojalateria_pintura',
    aliases: [
      'hojalateria',
      'hojalatería',
      'pintura automotriz',
      'golpe de carro',
      'carro golpeado',
      'reparacion de carroceria',
      'reparación de carrocería',
      'enderezado',
    ],
    categoriaHint: 'Automotriz',
    subcategoriaHint: 'Hojalatería y pintura',
    servicios: [
      'Reparación de carrocería',
      'Pintura automotriz',
      'Reparación de golpes automotrices',
      'Restauración de pintura',
    ],
  },
  {
    clave: 'gruas',
    aliases: [
      'grua',
      'grúa',
      'gruas',
      'grúas',
      'auxilio vial',
      'remolque',
      'traslado de vehiculo',
      'traslado de vehículo',
    ],
    categoriaHint: 'Automotriz',
    subcategoriaHint: 'Servicio de grúas',
    servicios: [
      'Grúa para automóviles',
      'Grúa para camionetas',
      'Auxilio vial con grúa',
      'Traslado de vehículos',
    ],
  },
  {
    clave: 'cambio_aceite',
    aliases: [
      'cambio de aceite',
      'aceite',
      'filtro de aceite',
      'lubricacion',
      'lubricación',
      'aceite sintetico',
      'aceite sintético',
    ],
    categoriaHint: 'Automotriz',
    subcategoriaHint: 'Cambio de aceite',
    servicios: [
      'Cambio de aceite automotriz',
      'Cambio de filtro de aceite',
      'Lubricación automotriz',
      'Cambio de aceite sintético',
    ],
  },
  {
    clave: 'diagnostico_automotriz',
    aliases: [
      'diagnostico automotriz',
      'diagnóstico automotriz',
      'escaneo automotriz',
      'scanner automotriz',
      'obd2',
      'falla electronica',
      'falla electrónica',
      'sensores',
    ],
    categoriaHint: 'Automotriz',
    subcategoriaHint: 'Diagnóstico automotriz',
    servicios: [
      'Escaneo automotriz OBD2',
      'Diagnóstico electrónico automotriz',
      'Diagnóstico de sensores automotrices',
      'Diagnóstico de motor computarizado',
    ],
  },

  // =========================================================
  // TIENDAS Y NEGOCIOS
  // =========================================================
  {
    clave: 'abarrotes',
    aliases: [
      'abarrotes',
      'tienda de abarrotes',
      'tiendita',
      'tiendita de la esquina',
      'miscelanea',
      'miscelánea',
      'abarrotera',
      // Coloquial mexicano
      'chesco',
      'chescos',
      'chesco frio',
      'donde venden chescos',
      'donde hay chescos',
      'refresco',
      'refrescos',
      'sodas',
      'donde comprar refresco',
      'changarrito',
      'estanquillo',
      'expendio',
      'minisuper',
      'mini super',
      'oxxo',
      'seven eleven',
      '7 eleven',
      'botanas',
      'frituras',
      'papitas',
      'chicharrones',
      'dulces',
      'dulceria',
      'dulcería',
      'chicles',
      'cigarros',
      'cigarro',
      'tabaco',
      'hielo',
      'agua',
      'donde hay agua',
      'leche',
      'huevo',
      'frijoles',
      'azucar',
      'azúcar',
      'sal',
      'aceite de cocina',
      'despensa',
      'despensa basica',
      'despensa básica',
      'lo que necesito del super',
      'mandado',
    ],
    categoriaHint: 'Tiendas y Negocios',
    subcategoriaHint: 'Tiendas de abarrotes',
    servicios: [
      'Abarrotes básicos',
      'Snacks y botanas',
      'Bebidas y refrescos',
      'Lácteos y huevo',
    ],
  },
  {
    clave: 'supermercados',
    aliases: [
      'super',
      'supermercado',
      'supermercados',
      'super mercado',
      'despensa',
      'mandado',
    ],
    categoriaHint: 'Tiendas y Negocios',
    subcategoriaHint: 'Supermercados',
    servicios: [
      'Despensa completa',
      'Frutas y verduras de supermercado',
      'Carnes y embutidos',
      'Artículos de limpieza del hogar',
    ],
  },
  {
    clave: 'tiendas_ropa',
    aliases: [
      'ropa',
      'tienda de ropa',
      'boutique',
      'ropa para mujer',
      'ropa para hombre',
      'ropa infantil',
      'ropa vaquera',
    ],
    categoriaHint: 'Tiendas y Negocios',
    subcategoriaHint: 'Tiendas de ropa',
    servicios: [
      'Ropa para mujer',
      'Ropa para hombre',
      'Ropa infantil',
      'Ropa deportiva casual',
      'Ropa vaquera',
    ],
  },
  {
    clave: 'zapaterias',
    aliases: [
      'zapateria',
      'zapatería',
      'zapaterias',
      'zapaterías',
      'zapatos',
      'tenis',
      'botas',
      'calzado',
      'bota vaquera',
    ],
    categoriaHint: 'Tiendas y Negocios',
    subcategoriaHint: 'Zapaterías',
    servicios: [
      'Calzado para mujer',
      'Calzado para hombre',
      'Calzado infantil',
      'Tenis deportivos',
      'Botas vaqueras',
    ],
  },
  {
    clave: 'sombrererias',
    aliases: [
      'sombrero',
      'sombreros',
      'sombrereria',
      'sombrerería',
      'sombrererias',
      'sombrererías',
      'gorra',
      'gorras',
      'cachucha',
      'vaquero',
    ],
    categoriaHint: 'Tiendas y Negocios',
    subcategoriaHint: 'Sombrererías',
    servicios: [
      'Sombreros vaqueros',
      'Gorras y cachuchas',
      'Accesorios vaqueros',
    ],
  },
  {
    clave: 'electronica',
    aliases: [
      'electronica',
      'electrónica',
      'tienda de electronica',
      'tienda de electrónica',
      'computadoras',
      'laptops',
      'pantallas',
      'televisores',
      'bocinas',
      'consolas',
    ],
    categoriaHint: 'Tiendas y Negocios',
    subcategoriaHint: 'Tiendas de electrónica',
    servicios: [
      'Computadoras y laptops',
      'Pantallas y televisores',
      'Audio y bocinas',
      'Videojuegos y consolas',
    ],
  },
  {
    clave: 'tiendas_celulares',
    aliases: [
      'celular',
      'celulares',
      'tienda de celulares',
      'telefono',
      'teléfono',
      'telefonos',
      'teléfonos',
      'micas',
      'fundas',
      'cargadores',
      'recargas',
    ],
    categoriaHint: 'Tiendas y Negocios',
    subcategoriaHint: 'Tiendas de celulares',
    servicios: [
      'Celulares nuevos',
      'Accesorios para celular',
      'Recargas telefónicas',
      'Equipos liberados',
    ],
  },
  {
    clave: 'papelerias',
    aliases: [
      'papeleria',
      'papelería',
      'papelerias',
      'papelerías',
      'utiles escolares',
      'útiles escolares',
      'impresiones',
      'copias',
      'material escolar',
    ],
    categoriaHint: 'Tiendas y Negocios',
    subcategoriaHint: 'Papelerías',
    servicios: [
      'Útiles escolares',
      'Artículos de oficina',
      'Impresiones y copias',
      'Material para manualidades',
    ],
  },
  {
    clave: 'regalos',
    aliases: [
      'regalos',
      'tienda de regalos',
      'globos',
      'peluches',
      'detalles',
      'regalo personalizado',
      'envoltura de regalos',
    ],
    categoriaHint: 'Tiendas y Negocios',
    subcategoriaHint: 'Tiendas de regalos',
    servicios: [
      'Regalos personalizados',
      'Globos y arreglos',
      'Peluches y detalles',
      'Envoltura de regalos',
    ],
  },
  {
    clave: 'tiendas_mascotas',
    aliases: [
      'tienda de mascotas',
      'pet shop',
      'mascotas',
      'croquetas',
      'alimento para perro',
      'alimento para gato',
      'camas para mascotas',
    ],
    categoriaHint: 'Tiendas y Negocios',
    subcategoriaHint: 'Tiendas de mascotas',
    servicios: [
      'Alimento para perros',
      'Alimento para gatos',
      'Accesorios para mascotas',
      'Productos de higiene para mascotas',
    ],
  },
  {
    clave: 'naturistas',
    aliases: [
      'naturista',
      'naturistas',
      'tienda naturista',
      'suplementos',
      'hierbas',
      'productos naturales',
      'tes',
      'tés',
      'infusiones',
    ],
    categoriaHint: 'Tiendas y Negocios',
    subcategoriaHint: 'Tiendas naturistas',
    servicios: [
      'Suplementos alimenticios',
      'Productos herbales',
      'Tés e infusiones',
      'Alimentos saludables',
    ],
  },
  {
    clave: 'cosmeticos',
    aliases: [
      'cosmeticos',
      'cosméticos',
      'maquillaje',
      'labiales',
      'delineadores',
      'cuidado de la piel',
      'productos para uñas',
    ],
    categoriaHint: 'Tiendas y Negocios',
    subcategoriaHint: 'Tiendas de cosméticos',
    servicios: [
      'Maquillaje facial',
      'Labiales y delineadores',
      'Cuidado de la piel',
      'Productos para uñas',
    ],
  },

  // =========================================================
  // BELLEZA Y BIENESTAR
  // =========================================================
  {
    clave: 'salones_belleza',
    aliases: [
      'salon de belleza',
      'salón de belleza',
      'salones de belleza',
      'belleza',
      'peinado',
      'tinte',
      'corte femenino',
    ],
    categoriaHint: 'Belleza y Bienestar',
    subcategoriaHint: 'Salones de belleza',
    servicios: [
      'Corte de cabello femenino',
      'Peinado profesional',
      'Tratamiento capilar hidratante',
      'Aplicación de tinte capilar',
    ],
  },
  {
    clave: 'barberias',
    aliases: [
      'barber',
      'barbershop',
      'barberia',
      'barbería',
      'barberias',
      'barberías',
      'barba',
      'corte de hombre',
      'afeitado',
    ],
    categoriaHint: 'Belleza y Bienestar',
    subcategoriaHint: 'Barberías',
    servicios: [
      'Corte de cabello masculino',
      'Arreglo profesional de barba',
      'Afeitado clásico con navaja',
      'Diseño de barba personalizado',
    ],
  },
  {
    clave: 'esteticas',
    aliases: [
      'estetica',
      'estética',
      'esteticas',
      'estéticas',
      'keratina',
      'botox capilar',
      'peinados',
    ],
    categoriaHint: 'Belleza y Bienestar',
    subcategoriaHint: 'Estéticas',
    servicios: [
      'Tratamiento capilar reparador',
      'Aplicación de keratina capilar',
      'Aplicación de botox capilar',
      'Peinados para eventos sociales',
    ],
  },
  {
    clave: 'salones_unas',
    aliases: [
      'uñas',
      'unas',
      'salon de uñas',
      'salón de uñas',
      'manicure',
      'pedicure',
      'gelish',
      'acrilicas',
      'acrílicas',
      'nails',
    ],
    categoriaHint: 'Belleza y Bienestar',
    subcategoriaHint: 'Salones de uñas',
    servicios: [
      'Manicure profesional',
      'Pedicure profesional',
      'Uñas acrílicas esculturales',
      'Aplicación de gelish',
      'Diseño artístico de uñas',
    ],
  },
  {
    clave: 'spas',
    aliases: [
      'spa',
      'spas',
      'facial',
      'baño de vapor',
      'exfoliacion',
      'exfoliación',
      'relajacion',
      'relajación',
    ],
    categoriaHint: 'Belleza y Bienestar',
    subcategoriaHint: 'Spas',
    servicios: [
      'Masaje relajante de spa',
      'Tratamiento facial de spa',
      'Exfoliación corporal spa',
      'Baño de vapor spa',
    ],
  },
  {
    clave: 'masajes_terapeuticos',
    aliases: [
      'masaje',
      'masajes',
      'masaje terapeutico',
      'masaje terapéutico',
      'descontracturante',
      'tejido profundo',
      'masaje deportivo',
    ],
    categoriaHint: 'Belleza y Bienestar',
    subcategoriaHint: 'Masajes terapéuticos',
    servicios: [
      'Masaje descontracturante',
      'Masaje deportivo terapéutico',
      'Masaje de tejido profundo',
      'Masaje relajante corporal',
    ],
  },
  {
    clave: 'gimnasios',
    aliases: [
      'gimnasio',
      'gym',
      'pesas',
      'crossfit',
      'entrenamiento funcional',
      'entrenador personal',
      'fitnes',
      'fitness',
    ],
    categoriaHint: 'Belleza y Bienestar',
    subcategoriaHint: 'Gimnasios',
    servicios: [
      'Entrenamiento con pesas',
      'Clases de crossfit',
      'Entrenamiento funcional',
      'Entrenamiento personal fitness',
    ],
  },
  {
    clave: 'yoga',
    aliases: [
      'yoga',
      'clases de yoga',
      'meditacion',
      'meditación',
      'yoga terapeutico',
      'yoga terapéutico',
    ],
    categoriaHint: 'Belleza y Bienestar',
    subcategoriaHint: 'Estudios de yoga',
    servicios: [
      'Clases de yoga para principiantes',
      'Clases de yoga avanzado',
      'Yoga de relajación y meditación',
      'Yoga terapéutico',
    ],
  },
  {
    clave: 'pilates',
    aliases: [
      'pilates',
      'pilates reformer',
      'reformer',
      'pilates terapeutico',
      'pilates terapéutico',
    ],
    categoriaHint: 'Belleza y Bienestar',
    subcategoriaHint: 'Estudios de pilates',
    servicios: [
      'Clases de pilates mat',
      'Pilates con reformer',
      'Pilates terapéutico',
      'Pilates para fortalecimiento corporal',
    ],
  },
  {
    clave: 'clinicas_esteticas',
    aliases: [
      'clinica estetica',
      'clínica estética',
      'clinicas esteticas',
      'clínicas estéticas',
      'botox',
      'rellenos faciales',
      'antiacne',
      'antiacné',
    ],
    categoriaHint: 'Belleza y Bienestar',
    subcategoriaHint: 'Clínicas estéticas',
    servicios: [
      'Tratamiento facial estético',
      'Aplicación de botox estético',
      'Rellenos faciales estéticos',
      'Tratamientos antiacné clínicos',
    ],
  },
  {
    clave: 'depilacion',
    aliases: [
      'depilacion',
      'depilación',
      'cera',
      'depilacion laser',
      'depilación láser',
      'depilacion facial',
      'depilación facial',
    ],
    categoriaHint: 'Belleza y Bienestar',
    subcategoriaHint: 'Depilación',
    servicios: [
      'Depilación con cera',
      'Depilación láser',
      'Depilación facial',
      'Depilación corporal completa',
    ],
  },
  {
    clave: 'maquillaje',
    aliases: [
      'maquillaje',
      'maquillista',
      'makeup',
      'maquillaje para novia',
      'maquillaje artistico',
      'maquillaje artístico',
    ],
    categoriaHint: 'Belleza y Bienestar',
    subcategoriaHint: 'Salones de maquillaje',
    servicios: [
      'Maquillaje profesional social',
      'Maquillaje para novia',
      'Maquillaje artístico profesional',
      'Maquillaje de día natural',
    ],
  },
  {
    clave: 'peluquerias',
    aliases: [
      'peluqueria',
      'peluquería',
      'peluquerias',
      'peluquerías',
      'corte unisex',
      'alaciado',
      'tratamiento capilar',
    ],
    categoriaHint: 'Belleza y Bienestar',
    subcategoriaHint: 'Peluquerías',
    servicios: [
      'Corte de cabello unisex',
      'Peinado para eventos',
      'Tratamiento capilar nutritivo',
      'Alaciado permanente capilar',
    ],
  },

  // =========================================================
  // EDUCACIÓN Y CURSOS
  // =========================================================
  {
    clave: 'academias_idiomas',
    aliases: [
      'ingles',
      'inglés',
      'frances',
      'francés',
      'aleman',
      'alemán',
      'italiano',
      'japones',
      'japonés',
      'academia de idiomas',
      'clases de ingles',
      'clases de inglés',
    ],
    categoriaHint: 'Educación y Cursos',
    subcategoriaHint: 'Academias de idiomas',
    servicios: [
      'Clases de inglés profesional',
      'Clases de francés académico',
      'Clases de alemán conversacional',
      'Clases de italiano básico',
      'Clases de japonés inicial',
    ],
  },
  {
    clave: 'clases_particulares',
    aliases: [
      'clases particulares',
      'asesorias',
      'asesorías',
      'regularizacion',
      'regularización',
      'matematicas',
      'matemáticas',
      'fisica',
      'física',
      'quimica',
      'química',
    ],
    categoriaHint: 'Educación y Cursos',
    subcategoriaHint: 'Clases particulares',
    servicios: [
      'Clases particulares de matemáticas',
      'Clases particulares de física',
      'Clases particulares de química',
      'Clases particulares de inglés escolar',
    ],
  },
  {
    clave: 'cursos_computacion',
    aliases: [
      'computacion',
      'computación',
      'excel',
      'word',
      'informatica',
      'informática',
      'diseño grafico',
      'diseño gráfico',
    ],
    categoriaHint: 'Educación y Cursos',
    subcategoriaHint: 'Cursos de computación',
    servicios: [
      'Curso de Microsoft Excel',
      'Curso de Microsoft Word',
      'Curso de informática básica',
      'Curso de diseño gráfico digital',
    ],
  },
  {
    clave: 'escuelas_musica',
    aliases: [
      'musica',
      'música',
      'guitarra',
      'piano',
      'bateria',
      'batería',
      'canto',
      'escuela de musica',
      'escuela de música',
    ],
    categoriaHint: 'Educación y Cursos',
    subcategoriaHint: 'Escuelas de música',
    servicios: [
      'Clases de guitarra musical',
      'Clases de piano musical',
      'Clases de batería musical',
      'Clases de canto profesional',
    ],
  },
  {
    clave: 'academias_baile',
    aliases: [
      'baile',
      'academia de baile',
      'salsa',
      'bachata',
      'baile urbano',
      'hip hop',
      'danza moderna',
    ],
    categoriaHint: 'Educación y Cursos',
    subcategoriaHint: 'Academias de baile',
    servicios: [
      'Clases de baile moderno',
      'Clases de salsa profesional',
      'Clases de bachata',
      'Clases de baile urbano',
    ],
  },
  {
    clave: 'escuelas_arte',
    aliases: [
      'arte',
      'pintura',
      'dibujo',
      'ilustracion',
      'ilustración',
      'escultura',
      'escuela de arte',
    ],
    categoriaHint: 'Educación y Cursos',
    subcategoriaHint: 'Escuelas de arte',
    servicios: [
      'Clases de pintura artística',
      'Clases de dibujo artístico',
      'Clases de ilustración artística',
      'Clases de escultura artística',
    ],
  },
  {
    clave: 'cursos_cocina',
    aliases: [
      'curso de cocina',
      'clases de cocina',
      'reposteria',
      'repostería',
      'panaderia',
      'panadería',
      'cocina mexicana',
      'cocina internacional',
    ],
    categoriaHint: 'Educación y Cursos',
    subcategoriaHint: 'Cursos de cocina',
    servicios: [
      'Curso de cocina mexicana',
      'Curso de repostería profesional',
      'Curso de cocina internacional',
      'Curso de panadería artesanal',
    ],
  },
  {
    clave: 'escuelas_programacion',
    aliases: [
      'programacion',
      'programación',
      'python',
      'backend',
      'web',
      'apps',
      'aplicaciones moviles',
      'aplicaciones móviles',
      'desarrollo web',
      'curso de programacion',
      'curso de programación',
    ],
    categoriaHint: 'Educación y Cursos',
    subcategoriaHint: 'Escuelas de programación',
    servicios: [
      'Curso de programación web',
      'Curso de desarrollo de aplicaciones móviles',
      'Curso de programación en Python',
      'Curso de desarrollo backend',
    ],
  },
  {
    clave: 'escuelas_manejo',
    aliases: [
      'manejo',
      'escuela de manejo',
      'clases de manejo',
      'manejar',
      'licencia',
      'manejo defensivo',
      'automatico',
      'automático',
    ],
    categoriaHint: 'Educación y Cursos',
    subcategoriaHint: 'Escuelas de manejo',
    servicios: [
      'Curso de manejo para principiantes',
      'Curso de manejo defensivo',
      'Curso de manejo para licencia',
      'Curso de manejo automático',
    ],
  },

  // =========================================================
  // HOGAR Y CONSTRUCCIÓN
  // =========================================================
  {
    clave: 'materiales_construccion',
    aliases: [
      'materiales de construccion',
      'materiales de construcción',
      'cemento',
      'arena',
      'grava',
      'block',
      'tabique',
      'varilla',
      'acero',
    ],
    categoriaHint: 'Hogar y Construcción',
    subcategoriaHint: 'Materiales de construcción',
    servicios: [
      'Venta de cemento y mortero',
      'Venta de arena y grava',
      'Venta de block y tabique',
      'Venta de varilla y acero',
    ],
  },
  {
    clave: 'tiendas_pintura',
    aliases: [
      'pintura',
      'tienda de pintura',
      'vinilica',
      'vinílica',
      'impermeabilizante',
      'brochas',
      'rodillos',
      'esmalte',
    ],
    categoriaHint: 'Hogar y Construcción',
    subcategoriaHint: 'Tiendas de pintura',
    servicios: [
      'Venta de pintura vinílica',
      'Venta de esmalte para herrería',
      'Venta de impermeabilizante líquido',
      'Venta de accesorios para pintar',
    ],
  },
  {
    clave: 'plomeria',
    aliases: [
      'plomero',
      'plomeria',
      'plomería',
      'fuga',
      'fuga de agua',
      'destapar drenaje',
      'destape',
      'tuberia',
      'tubería',
      'baño',
      'lavabo',
      'wc',
    ],
    categoriaHint: 'Hogar y Construcción',
    subcategoriaHint: 'Plomería',
    servicios: [
      'Reparación de fugas de agua',
      'Instalación de tubería hidráulica',
      'Destape de drenaje doméstico',
      'Instalación de muebles de baño',
    ],
  },
  {
    clave: 'electricistas',
    aliases: [
      'electricista',
      'electricistas',
      'electrico',
      'eléctrico',
      'corto',
      'cortocircuito',
      'contacto',
      'apagador',
      'luminaria',
      'lampara',
      'lámpara',
    ],
    categoriaHint: 'Hogar y Construcción',
    subcategoriaHint: 'Electricistas',
    servicios: [
      'Instalación eléctrica residencial',
      'Reparación de cortocircuitos',
      'Instalación de contactos y apagadores',
      'Instalación de luminarias interiores',
    ],
  },
  {
    clave: 'carpinterias',
    aliases: [
      'carpintero',
      'carpinteria',
      'carpintería',
      'muebles de madera',
      'puertas de madera',
      'closet',
      'closets',
      'cocina integral',
    ],
    categoriaHint: 'Hogar y Construcción',
    subcategoriaHint: 'Carpinterías',
    servicios: [
      'Fabricación de muebles de madera',
      'Reparación de puertas de madera',
      'Fabricación de closets a medida',
      'Instalación de cocinas integrales de madera',
    ],
  },
  {
    clave: 'albaniles',
    aliases: [
      'albañil',
      'albanil',
      'albañiles',
      'albaniles',
      'muros',
      'bardas',
      'aplanado',
      'repellado',
      'colado',
      'remodelacion',
      'remodelación',
    ],
    categoriaHint: 'Hogar y Construcción',
    subcategoriaHint: 'Albañiles',
    servicios: [
      'Construcción de muros y bardas',
      'Aplanados y repellados de obra',
      'Colado de losas y firmes',
      'Remodelación de espacios habitacionales',
    ],
  },
  {
    clave: 'cerrajerias',
    aliases: [
      'cerrajero',
      'cerrajeria',
      'cerrajería',
      'abrir chapa',
      'abrir puerta',
      'duplicado de llaves',
      'llaves',
      'chapa',
      'cerradura',
    ],
    categoriaHint: 'Hogar y Construcción',
    subcategoriaHint: 'Cerrajerías',
    servicios: [
      'Apertura de cerraduras residenciales',
      'Cambio de chapas de seguridad',
      'Duplicado de llaves convencionales',
      'Instalación de cerraduras de alta seguridad',
    ],
  },
  {
    clave: 'herrerias',
    aliases: [
      'herrero',
      'herreria',
      'herrería',
      'soldadura',
      'protecciones',
      'porton',
      'portón',
      'barandal',
      'barandales',
      'metalica',
      'metálica',
    ],
    categoriaHint: 'Hogar y Construcción',
    subcategoriaHint: 'Herrerías',
    servicios: [
      'Fabricación de protecciones metálicas',
      'Fabricación de portones de herrería',
      'Fabricación de barandales metálicos',
      'Reparación de estructuras metálicas',
    ],
  },
  {
    clave: 'impermeabilizacion',
    aliases: [
      'impermeabilizacion',
      'impermeabilización',
      'filtracion',
      'filtración',
      'humedad',
      'techo',
      'azotea',
      'membrana impermeable',
    ],
    categoriaHint: 'Hogar y Construcción',
    subcategoriaHint: 'Impermeabilización',
    servicios: [
      'Impermeabilización de techos residenciales',
      'Sellado de filtraciones en muros',
      'Aplicación de membrana impermeable',
      'Mantenimiento preventivo de impermeabilización',
    ],
  },
  {
    clave: 'vidrierias',
    aliases: [
      'vidriero',
      'vidrieria',
      'vidriería',
      'vidrio templado',
      'cancel de baño',
      'espejos',
      'ventana de vidrio',
      'cristal',
    ],
    categoriaHint: 'Hogar y Construcción',
    subcategoriaHint: 'Vidrierías',
    servicios: [
      'Instalación de vidrio templado',
      'Reparación de ventanas de vidrio',
      'Fabricación de canceles de baño',
      'Instalación de espejos decorativos',
    ],
  },
  {
    clave: 'instalacion_pisos',
    aliases: [
      'piso',
      'pisos',
      'instalacion de piso',
      'instalación de piso',
      'piso ceramico',
      'piso cerámico',
      'piso laminado',
      'piso vinilico',
      'piso vinílico',
      'loseta',
    ],
    categoriaHint: 'Hogar y Construcción',
    subcategoriaHint: 'Instalación de pisos',
    servicios: [
      'Colocación de piso cerámico',
      'Instalación de piso laminado',
      'Instalación de piso vinílico',
      'Nivelación de superficie para piso',
    ],
  },
  {
    clave: 'aire_acondicionado',
    aliases: [
      'aire acondicionado',
      'minisplit',
      'mini split',
      'instalar minisplit',
      'mantenimiento de aire',
      'recarga de gas',
      'clima',
    ],
    categoriaHint: 'Hogar y Construcción',
    subcategoriaHint: 'Instalación de aire acondicionado',
    servicios: [
      'Instalación de minisplit residencial',
      'Mantenimiento de aire acondicionado doméstico',
      'Recarga de gas refrigerante',
      'Reparación de fallas en minisplit',
    ],
  },
  {
    clave: 'reparacion_electrodomesticos',
    aliases: [
      'reparacion de electrodomesticos',
      'reparación de electrodomésticos',
      'lavadora',
      'refrigerador',
      'microondas',
      'estufa',
      'horno',
      'electrodomestico',
      'electrodoméstico',
    ],
    categoriaHint: 'Hogar y Construcción',
    subcategoriaHint: 'Reparación de electrodomésticos',
    servicios: [
      'Reparación de lavadoras domésticas',
      'Reparación de refrigeradores domésticos',
      'Reparación de microondas residenciales',
      'Reparación de estufas y hornos',
    ],
  },
  {
    clave: 'jardineria',
    aliases: [
      'jardinero',
      'jardineria',
      'jardinería',
      'poda',
      'jardin',
      'jardín',
      'pasto',
      'arboles',
      'árboles',
      'arbustos',
    ],
    categoriaHint: 'Hogar y Construcción',
    subcategoriaHint: 'Jardinería',
    servicios: [
      'Mantenimiento de jardines residenciales',
      'Diseño de jardines ornamentales',
      'Poda de árboles y arbustos',
      'Instalación de pasto natural o sintético',
    ],
  },
  {
    clave: 'fumigacion',
    aliases: [
      'fumigacion',
      'fumigación',
      'plagas',
      'cucarachas',
      'termitas',
      'desinfeccion',
      'desinfección',
      'control de plagas',
    ],
    categoriaHint: 'Hogar y Construcción',
    subcategoriaHint: 'Fumigación',
    servicios: [
      'Control de plagas domésticas',
      'Fumigación contra cucarachas',
      'Fumigación contra termitas',
      'Desinfección de casas y negocios',
    ],
  },

  // =========================================================
  // MASCOTAS
  // =========================================================
  {
    clave: 'veterinarias',
    aliases: [
      'veterinaria',
      'veterinarias',
      'veterinario',
      'veterinarios',
      'vet',
      'mascota enferma',
      'consulta animal',
    ],
    categoriaHint: 'Mascotas',
    subcategoriaHint: 'Veterinarias',
    servicios: [
      'Consulta veterinaria general',
      'Vacunación para mascotas',
      'Desparasitación veterinaria',
      'Chequeo médico preventivo animal',
    ],
  },
  {
    clave: 'clinicas_veterinarias',
    aliases: [
      'clinica veterinaria',
      'clínica veterinaria',
      'clinicas veterinarias',
      'clínicas veterinarias',
      'cirugia veterinaria',
      'cirugía veterinaria',
      'hospitalizacion veterinaria',
      'hospitalización veterinaria',
    ],
    categoriaHint: 'Mascotas',
    subcategoriaHint: 'Clínicas veterinarias',
    servicios: [
      'Diagnóstico veterinario especializado',
      'Cirugía veterinaria menor',
      'Tratamiento veterinario para infecciones',
      'Hospitalización veterinaria temporal',
    ],
  },
  {
    clave: 'hospitales_veterinarios',
    aliases: [
      'hospital veterinario',
      'hospitales veterinarios',
      'urgencias veterinarias',
      'emergencia veterinaria',
      'veterinario 24 horas',
      'veterinario urgente',
    ],
    categoriaHint: 'Mascotas',
    subcategoriaHint: 'Hospitales veterinarios',
    servicios: [
      'Urgencias veterinarias 24 horas',
      'Cirugía veterinaria avanzada',
      'Hospitalización veterinaria intensiva',
      'Diagnóstico veterinario por imagen',
    ],
  },
  {
    clave: 'esteticas_caninas',
    aliases: [
      'estetica canina',
      'estética canina',
      'baño para perro',
      'baño de perro',
      'corte de pelo perro',
      'uñas perro',
      'oidos perro',
      'oídos perro',
    ],
    categoriaHint: 'Mascotas',
    subcategoriaHint: 'Estéticas caninas',
    servicios: [
      'Baño para perros',
      'Corte de pelo canino',
      'Limpieza de oídos para perros',
      'Corte de uñas para perros',
    ],
  },
  {
    clave: 'peluquerias_mascotas',
    aliases: [
      'peluqueria para mascotas',
      'peluquería para mascotas',
      'peluquerias para mascotas',
      'peluquerías para mascotas',
      'pelaje',
      'corte para gatos',
      'antipulgas estetico',
      'antipulgas estético',
    ],
    categoriaHint: 'Mascotas',
    subcategoriaHint: 'Peluquerías para mascotas',
    servicios: [
      'Estilizado de pelaje para mascotas',
      'Cepillado profesional de mascotas',
      'Corte de pelo para gatos',
      'Tratamiento antipulgas estético',
    ],
  },
  {
    clave: 'alimento_mascotas',
    aliases: [
      'croquetas',
      'alimento para mascotas',
      'alimento para perro',
      'alimento para perros',
      'alimento para gato',
      'alimento para gatos',
      'alimento premium',
    ],
    categoriaHint: 'Mascotas',
    subcategoriaHint: 'Alimento para mascotas',
    servicios: [
      'Venta de alimento para perros',
      'Venta de alimento para gatos',
      'Venta de alimento para aves',
      'Venta de alimento premium para mascotas',
    ],
  },
  {
    clave: 'accesorios_mascotas',
    aliases: [
      'accesorios para mascotas',
      'juguetes para mascotas',
      'camas para mascotas',
      'correas',
      'collares',
      'transportadora',
      'transportadoras',
    ],
    categoriaHint: 'Mascotas',
    subcategoriaHint: 'Accesorios para mascotas',
    servicios: [
      'Venta de juguetes para mascotas',
      'Venta de camas para mascotas',
      'Venta de collares y correas',
      'Venta de transportadoras para mascotas',
    ],
  },
  {
    clave: 'guarderias_mascotas',
    aliases: [
      'guarderia para mascotas',
      'guardería para mascotas',
      'guarderia canina',
      'guardería canina',
      'cuidado de mascotas',
      'perro guarderia',
      'perro guardería',
    ],
    categoriaHint: 'Mascotas',
    subcategoriaHint: 'Guarderías para mascotas',
    servicios: [
      'Guardería diurna para perros',
      'Cuidado temporal de mascotas',
      'Área de juego para mascotas',
      'Socialización supervisada de perros',
    ],
  },
  {
    clave: 'hoteles_mascotas',
    aliases: [
      'hotel para perros',
      'hotel para mascotas',
      'hospedaje para perros',
      'hospedaje para gatos',
      'hotel canino',
      'cuidado nocturno mascota',
    ],
    categoriaHint: 'Mascotas',
    subcategoriaHint: 'Hoteles para mascotas',
    servicios: [
      'Hospedaje para perros',
      'Hospedaje para gatos',
      'Hotel vacacional para mascotas',
      'Cuidado nocturno de mascotas',
    ],
  },
  {
    clave: 'adiestramiento_mascotas',
    aliases: [
      'adiestramiento',
      'entrenamiento de perros',
      'obediencia canina',
      'conducta animal',
      'entrenar perro',
      'adiestrador',
    ],
    categoriaHint: 'Mascotas',
    subcategoriaHint: 'Adiestramiento de mascotas',
    servicios: [
      'Entrenamiento básico para perros',
      'Entrenamiento de obediencia canina',
      'Corrección de conducta animal',
      'Entrenamiento profesional de mascotas',
    ],
  },
  {
    clave: 'paseadores_perros',
    aliases: [
      'paseador de perros',
      'paseadores de perros',
      'pasear perro',
      'caminar perro',
      'ejercicio para perro',
    ],
    categoriaHint: 'Mascotas',
    subcategoriaHint: 'Paseadores de perros',
    servicios: [
      'Paseo diario para perros',
      'Paseo recreativo para perros',
      'Paseo grupal de perros',
      'Ejercicio guiado para perros',
    ],
  },
  {
    clave: 'veterinarios_domicilio',
    aliases: [
      'veterinario a domicilio',
      'veterinarios a domicilio',
      'consulta veterinaria a domicilio',
      'vacunas a domicilio mascota',
      'desparasitacion a domicilio mascota',
      'desparasitación a domicilio mascota',
    ],
    categoriaHint: 'Mascotas',
    subcategoriaHint: 'Veterinarios a domicilio',
    servicios: [
      'Consulta veterinaria a domicilio',
      'Vacunación veterinaria a domicilio',
      'Desparasitación veterinaria en casa',
      'Chequeo veterinario domiciliario',
    ],
  },

  // =========================================================
  // ENTRETENIMIENTO
  // =========================================================
  {
    clave: 'cines',
    aliases: [
      'cine',
      'cines',
      'peliculas',
      'películas',
      'cine vip',
      'cine 3d',
      'cinema',
    ],
    categoriaHint: 'Entretenimiento',
    subcategoriaHint: 'Cines',
    servicios: [
      'Cine 2D',
      'Cine 3D',
      'Cine VIP',
      'Cine familiar',
    ],
  },
  {
    clave: 'bares',
    aliases: [
      'bar',
      'bares',
      'cocteles',
      'cocteles',
      'cocteleria',
      'coctelería',
      'musica en vivo',
      'música en vivo',
      'bar lgbt',
      'bar gay',
    ],
    categoriaHint: 'Entretenimiento',
    subcategoriaHint: 'Bares',
    servicios: [
      'Bar con música en vivo',
      'Bar de coctelería',
      'Bar para comunidad LGBT',
    ],
  },
  {
    clave: 'antros_discotecas',
    aliases: [
      'antro',
      'antros',
      'discoteca',
      'discotecas',
      'antro lgbt',
      'antro gay',
      'antro con dj',
      'dj en vivo',
      'musica electronica',
      'música electrónica',
      'musica regional',
      'música regional',
    ],
    categoriaHint: 'Entretenimiento',
    subcategoriaHint: 'Antros y discotecas',
    servicios: [
      'Antros de música electrónica',
      'Antro de música regional',
      'Antro con DJ en vivo',
      'Antro LGBT',
    ],
  },
  {
    clave: 'karaokes',
    aliases: [
      'karaoke',
      'karaokes',
      'karaoke bar',
      'cantar karaoke',
      'cabina de karaoke',
    ],
    categoriaHint: 'Entretenimiento',
    subcategoriaHint: 'Karaokes',
    servicios: [
      'Karaoke con cabinas privadas',
      'Karaoke con escenario',
      'Karaoke bar',
      'Karaoke temático',
    ],
  },
  {
    clave: 'billar',
    aliases: [
      'billar',
      'billares',
      'mesa de billar',
      'pool',
      'billar con bar',
      'torneo de billar',
    ],
    categoriaHint: 'Entretenimiento',
    subcategoriaHint: 'Billar',
    servicios: [
      'Billar profesional',
      'Billar recreativo',
      'Billar con bar',
      'Billar con torneos',
    ],
  },
  {
    clave: 'boliches',
    aliases: [
      'boliche',
      'boliches',
      'bowling',
      'boliche familiar',
      'boliche nocturno',
    ],
    categoriaHint: 'Entretenimiento',
    subcategoriaHint: 'Boliches',
    servicios: [
      'Boliche familiar',
      'Boliche con restaurante',
      'Boliche nocturno',
      'Boliche con eventos',
    ],
  },
  {
    clave: 'salones_eventos',
    aliases: [
      'salon de eventos',
      'salón de eventos',
      'salones de eventos',
      'salon para bodas',
      'salón para bodas',
      'salon para fiestas',
      'salón para fiestas',
      'quinceañera',
      'quinceanera',
    ],
    categoriaHint: 'Entretenimiento',
    subcategoriaHint: 'Salones de eventos',
    servicios: [
      'Salón para bodas',
      'Salón para fiestas',
      'Salón para eventos corporativos',
      'Salón para quinceañeras',
    ],
  },
  {
    clave: 'teatros',
    aliases: [
      'teatro',
      'teatros',
      'obra',
      'obras',
      'teatro musical',
      'teatro infantil',
      'obra dramatica',
      'obra dramática',
    ],
    categoriaHint: 'Entretenimiento',
    subcategoriaHint: 'Teatros',
    servicios: [
      'Teatro de obras dramáticas',
      'Teatro musical',
      'Teatro experimental',
      'Teatro infantil',
    ],
  },
  {
    clave: 'videojuegos',
    aliases: [
      'videojuegos',
      'arcade',
      'gaming center',
      'xbox',
      'playstation',
      'maquinitas',
      'torneos de videojuegos',
      'realidad virtual',
    ],
    categoriaHint: 'Entretenimiento',
    subcategoriaHint: 'Centros de videojuegos',
    servicios: [
      'Arcade de videojuegos',
      'Gaming center',
      'Videojuegos en red',
      'Torneos de videojuegos',
    ],
  },
  {
    clave: 'parques_recreativos',
    aliases: [
      'parque recreativo',
      'parques recreativos',
      'picnic',
      'juegos infantiles',
      'caminata',
      'area deportiva',
      'área deportiva',
    ],
    categoriaHint: 'Entretenimiento',
    subcategoriaHint: 'Parques recreativos',
    servicios: [
      'Parque para picnic',
      'Parque con juegos infantiles',
      'Parque con áreas deportivas',
      'Parque para caminata',
    ],
  },
  {
    clave: 'parques_diversiones',
    aliases: [
      'parque de diversiones',
      'parques de diversiones',
      'juegos mecanicos',
      'juegos mecánicos',
      'parque acuatico',
      'parque acuático',
      'parque tematico',
      'parque temático',
    ],
    categoriaHint: 'Entretenimiento',
    subcategoriaHint: 'Parques de diversiones',
    servicios: [
      'Parque con juegos mecánicos',
      'Parque temático',
      'Parque acuático',
      'Parque familiar de atracciones',
    ],
  },
  {
    clave: 'conciertos_eventos_musicales',
    aliases: [
      'concierto',
      'conciertos',
      'evento musical',
      'eventos musicales',
      'festival',
      'festivales',
      'dj',
      'musica en vivo',
      'música en vivo',
    ],
    categoriaHint: 'Entretenimiento',
    subcategoriaHint: 'Conciertos y eventos musicales',
    servicios: [
      'Conciertos de música en vivo',
      'Festivales de música',
      'Eventos musicales al aire libre',
      'Eventos de DJ en vivo',
    ],
  },
  {
    clave: 'shows_espectaculos',
    aliases: [
      'show',
      'shows',
      'espectaculo',
      'espectáculo',
      'comedia',
      'stand up',
      'magia',
      'drag',
      'danza',
    ],
    categoriaHint: 'Entretenimiento',
    subcategoriaHint: 'Shows y espectáculos',
    servicios: [
      'Show de comedia',
      'Show de magia',
      'Show de danza',
      'Show de drag',
    ],
  },
  {
    clave: 'entretenimiento_familiar',
    aliases: [
      'entretenimiento familiar',
      'centro para niños',
      'juegos para niños',
      'trampolines',
      'centro familiar',
    ],
    categoriaHint: 'Entretenimiento',
    subcategoriaHint: 'Centros de entretenimiento familiar',
    servicios: [
      'Centro de juegos para niños',
      'Centro de trampolines',
      'Centro de juegos electrónicos',
      'Centro de entretenimiento familiar integral',
    ],
  },
  {
    clave: 'experiencias_recreativas',
    aliases: [
      'escape room',
      'realidad virtual',
      'experiencia interactiva',
      'experiencias recreativas',
      'actividad recreativa',
    ],
    categoriaHint: 'Entretenimiento',
    subcategoriaHint: 'Experiencias recreativas',
    servicios: [
      'Escape room',
      'Experiencias de realidad virtual',
      'Experiencias de aventura',
      'Experiencias interactivas',
    ],
  },

  // =========================================================
  // TURISMO Y VIAJES
  // =========================================================
  {
    clave: 'hoteles',
    aliases: [
      'hotel',
      'hoteles',
      'hospedaje',
      'alojamiento',
      'hotel con alberca',
      'hotel pet friendly',
      'hotel familiar',
      'hotel boutique',
    ],
    categoriaHint: 'Turismo y Viajes',
    subcategoriaHint: 'Hoteles',
    servicios: [
      'Hotel boutique',
      'Hotel con alberca',
      'Hotel familiar',
      'Hotel pet friendly',
    ],
  },
  {
    clave: 'hostales',
    aliases: [
      'hostal',
      'hostales',
      'mochilero',
      'hostel',
      'habitacion compartida',
      'habitación compartida',
      'hostal centrico',
      'hostal céntrico',
    ],
    categoriaHint: 'Turismo y Viajes',
    subcategoriaHint: 'Hostales',
    servicios: [
      'Hostal para mochileros',
      'Hostal con habitaciones compartidas',
      'Hostal con ambiente juvenil',
      'Hostal céntrico',
    ],
  },
  {
    clave: 'cabanas',
    aliases: [
      'cabaña',
      'cabañas',
      'cabana',
      'cabanas',
      'cabaña romantica',
      'cabaña romántica',
      'cabaña familiar',
      'bosque',
      'montaña',
      'montana',
    ],
    categoriaHint: 'Turismo y Viajes',
    subcategoriaHint: 'Cabañas',
    servicios: [
      'Cabañas de montaña',
      'Cabañas en bosque',
      'Cabañas familiares',
      'Cabañas románticas',
    ],
  },
  {
    clave: 'departamentos_vacacionales',
    aliases: [
      'departamento vacacional',
      'departamentos vacacionales',
      'airbnb',
      'renta vacacional',
      'departamento amueblado',
      'por noche',
    ],
    categoriaHint: 'Turismo y Viajes',
    subcategoriaHint: 'Departamentos vacacionales',
    servicios: [
      'Departamento turístico amueblado',
      'Departamento vacacional con cocina',
      'Departamento vacacional familiar',
      'Departamento turístico por noche',
    ],
  },
  {
    clave: 'agencias_viajes',
    aliases: [
      'agencia de viajes',
      'agencias de viajes',
      'paquete vacacional',
      'vuelos y hoteles',
      'viaje nacional',
      'viaje internacional',
    ],
    categoriaHint: 'Turismo y Viajes',
    subcategoriaHint: 'Agencias de viajes',
    servicios: [
      'Agencia de viajes internacional',
      'Agencia de viajes nacional',
      'Paquetes vacacionales',
      'Reservación de vuelos y hoteles',
    ],
  },
  {
    clave: 'tours_turisticos',
    aliases: [
      'tour',
      'tours',
      'tour turistico',
      'tour turístico',
      'tour cultural',
      'tour gastronomico',
      'tour gastronómico',
      'tour a playas',
      'tour a pueblos magicos',
      'tour a pueblos mágicos',
    ],
    categoriaHint: 'Turismo y Viajes',
    subcategoriaHint: 'Tours turísticos',
    servicios: [
      'Tour a playas',
      'Tour cultural',
      'Tour gastronómico',
      'Tour a pueblos mágicos',
    ],
  },
  {
    clave: 'guias_turisticos',
    aliases: [
      'guia turistico',
      'guía turístico',
      'guia de turistas',
      'guía de turistas',
      'guia local',
      'guía local',
      'guia bilingue',
      'guía bilingüe',
    ],
    categoriaHint: 'Turismo y Viajes',
    subcategoriaHint: 'Guías turísticos',
    servicios: [
      'Guía turístico certificado',
      'Guía turístico local',
      'Guía turístico cultural',
      'Guía turístico bilingüe',
    ],
  },
  {
    clave: 'renta_autos',
    aliases: [
      'renta de autos',
      'renta de auto',
      'alquiler de autos',
      'car rental',
      'auto por dia',
      'auto por día',
      'renta de carro',
    ],
    categoriaHint: 'Turismo y Viajes',
    subcategoriaHint: 'Renta de autos',
    servicios: [
      'Renta de autos económicos',
      'Renta de autos familiares',
      'Renta de autos de lujo',
      'Renta de autos por día',
    ],
  },
  {
    clave: 'transporte_turistico',
    aliases: [
      'transporte turistico',
      'transporte turístico',
      'traslado aeropuerto',
      'shuttle',
      'transporte privado',
      'transporte grupal',
    ],
    categoriaHint: 'Turismo y Viajes',
    subcategoriaHint: 'Transporte turístico',
    servicios: [
      'Transporte turístico privado',
      'Transporte turístico grupal',
      'Transporte turístico aeropuerto',
      'Transporte turístico regional',
    ],
  },
  {
    clave: 'renta_bicicletas',
    aliases: [
      'renta de bicicletas',
      'renta de bici',
      'bicicletas',
      'bicis',
      'bicicleta electrica',
      'bicicleta eléctrica',
      'tour en bicicleta',
    ],
    categoriaHint: 'Turismo y Viajes',
    subcategoriaHint: 'Renta de bicicletas',
    servicios: [
      'Renta de bicicletas urbanas',
      'Renta de bicicletas de montaña',
      'Renta de bicicletas eléctricas',
      'Tours en bicicleta',
    ],
  },
  {
    clave: 'renta_cuatrimotos',
    aliases: [
      'cuatrimoto',
      'cuatrimotos',
      'atv',
      'razer',
      'tour en cuatrimoto',
      'renta de cuatrimoto',
      'cuatrimoto en playa',
    ],
    categoriaHint: 'Turismo y Viajes',
    subcategoriaHint: 'Renta de cuatrimotos',
    servicios: [
      'Cuatrimotos para aventura',
      'Tours en cuatrimoto',
      'Renta de ATV todoterreno',
      'Cuatrimotos en playa',
    ],
  },
  {
    clave: 'renta_lanchas',
    aliases: [
      'lancha',
      'lanchas',
      'renta de lancha',
      'tour en lancha',
      'paseo en lancha',
      'lancha para pesca',
    ],
    categoriaHint: 'Turismo y Viajes',
    subcategoriaHint: 'Renta de lanchas',
    servicios: [
      'Renta de lancha privada',
      'Tour en lancha',
      'Lancha para pesca',
      'Lancha recreativa familiar',
    ],
  },
  {
    clave: 'parques_turisticos',
    aliases: [
      'parque turistico',
      'parque turístico',
      'parques turisticos',
      'parques turísticos',
      'parque natural',
      'parque ecologico',
      'parque ecológico',
      'parque historico',
      'parque histórico',
    ],
    categoriaHint: 'Turismo y Viajes',
    subcategoriaHint: 'Parques turísticos',
    servicios: [
      'Parque natural',
      'Parque ecológico',
      'Parque temático turístico',
      'Parque histórico',
    ],
  },
  {
    clave: 'aventura',
    aliases: [
      'aventura',
      'tirolesa',
      'rapel',
      'senderismo',
      'kayak',
      'actividad extrema',
      'deportes extremos',
    ],
    categoriaHint: 'Turismo y Viajes',
    subcategoriaHint: 'Experiencias de aventura',
    servicios: [
      'Tirolesa',
      'Rapel',
      'Senderismo guiado',
      'Kayak recreativo',
    ],
  },
  {
    clave: 'ecoturismo',
    aliases: [
      'ecoturismo',
      'turismo ecologico',
      'turismo ecológico',
      'observacion de aves',
      'observación de aves',
      'observacion de fauna',
      'observación de fauna',
      'turismo sustentable',
    ],
    categoriaHint: 'Turismo y Viajes',
    subcategoriaHint: 'Ecoturismo',
    servicios: [
      'Turismo ecológico',
      'Observación de fauna',
      'Observación de aves',
      'Turismo sustentable',
    ],
  },
  {
    clave: 'campamentos_turisticos',
    aliases: [
      'campamento',
      'campamentos',
      'camping',
      'acampar',
      'camping familiar',
      'camping con servicios',
      'camping en bosque',
    ],
    categoriaHint: 'Turismo y Viajes',
    subcategoriaHint: 'Campamentos turísticos',
    servicios: [
      'Camping familiar',
      'Camping en bosque',
      'Camping de aventura',
      'Camping con servicios',
    ],
  },
  {
    clave: 'miradores_turisticos',
    aliases: [
      'mirador',
      'miradores',
      'vista panoramica',
      'vista panorámica',
      'mirador fotografico',
      'mirador fotográfico',
    ],
    categoriaHint: 'Turismo y Viajes',
    subcategoriaHint: 'Miradores turísticos',
    servicios: [
      'Mirador panorámico',
      'Mirador natural',
      'Mirador urbano',
      'Mirador fotográfico',
    ],
  },

  // =========================================================
  // CASOS MIXTOS / ATAJOS DE BÚSQUEDA ÚTILES
  // =========================================================
  {
    clave: 'mascotas_tienda',
    aliases: [
      'petshop',
      'pet shop',
      'tienda pet',
      'tienda petshop',
    ],
    categoriaHint: 'Tiendas y Negocios',
    subcategoriaHint: 'Tiendas de mascotas',
    servicios: [
      'Alimento para perros',
      'Alimento para gatos',
      'Accesorios para mascotas',
    ],
  },
  {
    clave: 'bares_lgbt',
    aliases: [
      'bar lgbt',
      'bares lgbt',
      'bar gay',
      'bares gay',
      'bar para comunidad lgbt',
      'antro lgbt',
      'antro gay',
      'antro les',
      'antro lesbico',
    ],
    categoriaHint: 'Entretenimiento',
    subcategoriaHint: 'Bares',
    servicios: [
      'Bar para comunidad LGBT',
      'Antro LGBT',
      'Show de drag',
    ],
  },

  // =========================================================
  // COLOQUIAL MEXICANO — CATEGORÍAS NUEVAS
  // =========================================================
  {
    clave: 'fruterias_juguerias',
    aliases: [
      'fruteria', 'frutería', 'fruterias', 'fruterías',
      'jugos', 'jugo', 'jugeria', 'juguería',
      'licuado', 'licuados', 'licuadora',
      'aguas frescas', 'agua fresca',
      'agua de horchata', 'horchata',
      'agua de jamaica', 'jamaica',
      'agua de limón', 'agua de limon',
      'agua de tamarindo', 'tamarindo',
      'fruta picada', 'ensalada de frutas',
      'vitamina', 'vitaminas',
      'jugo de naranja', 'jugo verde',
      'jugo de zanahoria', 'jugo natural',
      'jugos naturales', 'barras de frutas',
      'donde hay jugos', 'donde venden jugos',
      'smoothie', 'smoothies', 'malteada', 'malteadas',
    ],
    categoriaHint: 'Comida y Restaurantes',
    subcategoriaHint: 'Fruterías y Juguerías',
    servicios: ['Jugos naturales', 'Licuados', 'Aguas frescas', 'Fruta picada', 'Smoothies'],
  },
  {
    clave: 'tortillerias',
    aliases: [
      'tortilleria', 'tortillería', 'tortillerias', 'tortillerías',
      'tortillas', 'tortilla',
      'tortillas de maiz', 'tortillas de maíz',
      'tortillas de harina',
      'kilo de tortillas',
      'tortillas calientes',
      'tortillas recién hechas',
      'tortillas recien hechas',
      'donde venden tortillas',
      'donde hay tortillas',
      'masa', 'masa de maiz', 'masa de maíz',
      'tortillero',
    ],
    categoriaHint: 'Comida y Restaurantes',
    subcategoriaHint: 'Tortillerías',
    servicios: ['Tortillas de maíz', 'Tortillas de harina', 'Masa'],
  },
  {
    clave: 'purificadoras',
    aliases: [
      'purificadora', 'purificadoras',
      'agua purificada', 'agua de purificadora',
      'garrafon', 'garrafón', 'garrafones',
      'pedir agua', 'agua a domicilio',
      'agua embotellada',
      'purificadora de agua',
      'donde comprar agua',
      'donde llenar garrafon',
      'donde llenar garrafón',
      'purificacion de agua', 'purificación de agua',
    ],
    categoriaHint: 'Tiendas y Negocios',
    subcategoriaHint: 'Purificadoras de agua',
    servicios: ['Agua purificada', 'Garrafones', 'Agua a domicilio'],
  },
  {
    clave: 'mercado_tianguis',
    aliases: [
      'mercado', 'mercados',
      'mercado municipal', 'mercado publico', 'mercado público',
      'tianguis',
      'plaza', 'bazar',
      'mercado sobre ruedas',
      'pulgas', 'mercado de pulgas',
      'segunda', 'ropa de segunda',
      'donde comprar barato',
      'remate', 'remates',
    ],
    categoriaHint: 'Tiendas y Negocios',
    subcategoriaHint: 'Mercados y Tianguis',
    servicios: ['Verduras', 'Frutas', 'Ropa de segunda', 'Comida de mercado'],
  },
  {
    clave: 'servicios_hogar',
    aliases: [
      // Plomería
      'plomero', 'plomeros', 'plomeria', 'plomería',
      'fuga de agua', 'tubo roto', 'drenaje tapado', 'baño tapado',
      'sanitario tapado', 'grifo descompuesto',
      // Electricidad
      'electricista', 'electricistas', 'electricidad',
      'corto circuito', 'instalacion electrica', 'instalación eléctrica',
      'luz que falla', 'apagón', 'apagon',
      // Gas
      'gasero', 'gas a domicilio', 'gas lp', 'gas natural',
      'tanque de gas', 'gas doméstico', 'gas domestico',
      // Albañilería
      'albanil', 'albañil', 'albanileria', 'albañilería',
      'construccion', 'construcción', 'remodelacion', 'remodelación',
      'poner azulejos', 'poner pisos',
      // Cerrajería
      'cerrajero', 'cerrajeros', 'cerrajeria', 'cerrajería',
      'llave atorada', 'puerta atorada', 'me quedé sin llave',
      'duplicado de llave', 'cambio de chapa',
      // Pintura
      'pintor', 'pintores', 'pintura de casa',
      'pintar cuarto', 'pintura de interiores',
      // Control de plagas
      'fumigacion', 'fumigación', 'fumigadora', 'fumigador',
      'control de plagas', 'exterminio', 'cucarachas', 'ratas',
      'chinches', 'alacranes', 'fumigaciones',
      // Jardinería
      'jardinero', 'jardineros', 'jardineria', 'jardinería',
      'poda', 'cortar pasto', 'jardin',
      // General
      'servicio a domicilio hogar', 'mantenimiento del hogar',
    ],
    categoriaHint: 'Servicios',
    subcategoriaHint: 'Servicios del hogar',
    servicios: [
      'Plomería', 'Electricidad', 'Gas a domicilio', 'Albañilería',
      'Cerrajería', 'Fumigación', 'Pintura de interiores', 'Jardinería',
    ],
  },
  {
    clave: 'celulares_tecnologia',
    aliases: [
      // Reparación
      'reparacion de celular', 'reparación de celular',
      'celular roto', 'pantalla rota', 'pantalla quebrada',
      'cambio de pantalla', 'cambio de bateria', 'cambio de batería',
      'tecnico de celulares', 'técnico de celulares',
      'celular no carga', 'celular apagado', 'celular mojado',
      'iphone roto', 'samsung roto', 'huawei roto',
      'reparar celular', 'compostura de celular',
      'desbloqueo de celular', 'celular bloqueado',
      'liberacion de celular', 'liberación de celular',
      // Venta
      'venta de celulares', 'celulares nuevos', 'celulares de segunda',
      'smartphone', 'telefono nuevo', 'teléfono nuevo',
      // Accesorios
      'accesorios de celular', 'funda de celular', 'case para celular',
      'mica para celular', 'vidrio templado', 'cargador de celular',
      'audifonos', 'audífonos', 'auriculares',
      // Computadoras
      'computadora', 'laptop', 'pc', 'computadora rota',
      'laptop rota', 'reparacion de computadora', 'reparación de computadora',
      'tecnico en computadoras', 'técnico en computadoras',
      // General
      'tecnologia', 'tecnología', 'electrónica',
    ],
    categoriaHint: 'Tecnología',
    subcategoriaHint: 'Celulares y Tecnología',
    servicios: [
      'Reparación de celulares', 'Cambio de pantalla', 'Cambio de batería',
      'Venta de celulares', 'Accesorios', 'Reparación de laptops',
    ],
  },
  {
    clave: 'caguamerias_licorerías',
    aliases: [
      // Coloquial caguama/cheve
      'caguameria', 'caguamería',
      'caguama', 'caguamas',
      'cheve', 'chevas', 'chelas',
      'michelada', 'micheladas',
      'chelada', 'cheladas',
      // Licores y vinos
      'licoreria', 'licorerías', 'licores',
      'vinos y licores', 'vineria', 'vinería',
      'vino', 'vinos',
      'vinoteca',
      'mezcal', 'mezcaleria', 'mezcalería',
      'tequila', 'tequileria', 'tequilería',
      'bebidas alcoholicas', 'bebidas alcohólicas',
      'pulque', 'pulqueria', 'pulquería',
      'cerveza', 'cervezas', 'cerveceria', 'cervecería',
      'chela', 'six pack', 'cartón de cervezas',
      'botella de vino', 'whisky', 'ron', 'vodka',
      'donde comprar alcohol', 'donde venden caguamas',
      'donde hay caguamas', 'donde hay cheves',
    ],
    categoriaHint: 'Tiendas y Negocios',
    subcategoriaHint: 'Licorerías y Caguamerías',
    servicios: ['Caguamas', 'Micheladas', 'Vinos', 'Licores', 'Cerveza fría'],
  },
  {
    clave: 'papelerias',
    aliases: [
      'papeleria', 'papelería', 'papelerias', 'papelerías',
      'utiles escolares', 'útiles escolares',
      'cuadernos', 'cuaderno',
      'lapices', 'lápices', 'plumas', 'colores',
      'impresiones', 'impresion', 'impresión',
      'copias', 'fotocopias', 'fotocopia',
      'plastificado', 'encuadernado',
      'material escolar', 'libreria', 'librería',
      'donde hacer copias', 'donde imprimir',
      'impresora', 'internet en papeleria',
    ],
    categoriaHint: 'Tiendas y Negocios',
    subcategoriaHint: 'Papelerías',
    servicios: ['Útiles escolares', 'Impresiones', 'Copias', 'Plastificado'],
  },
  {
    clave: 'ferreterias',
    aliases: [
      'ferreteria', 'ferretería', 'ferreterias', 'ferreterías',
      'tlapales', 'tlapaleria', 'tlapalería',
      'materiales de construccion', 'materiales de construcción',
      'herramientas',
      'clavos', 'tornillos', 'tuercas',
      'cemento', 'tabique', 'arena', 'grava',
      'pintura de pared',
      'manguera', 'tuberia', 'tubería',
      'cable electrico', 'cable eléctrico',
      'foco', 'focos', 'ampoco', 'ampoco',
      'llave de paso',
      'donde comprar materiales',
      'donde hay herramientas',
    ],
    categoriaHint: 'Tiendas y Negocios',
    subcategoriaHint: 'Ferreterías',
    servicios: ['Herramientas', 'Materiales de construcción', 'Pinturas', 'Plomería básica'],
  },
  {
    clave: 'carnicerías',
    aliases: [
      'carniceria', 'carnicería', 'carnicerías', 'carnicerías',
      'carne', 'carnes',
      'carne de res', 'carne molida', 'res',
      'pollo fresco', 'pollo crudo',
      'puerco', 'cerdo', 'carne de puerco', 'carne de cerdo',
      'chorizo', 'longaniza',
      'chuleta', 'costilla de res', 'costilla de cerdo',
      'bistec', 'filete',
      'molida', 'carne para asar',
      'tripas', 'menudo crudo',
      'donde venden carne',
      'carnitas de olla', 'chicharron',
    ],
    categoriaHint: 'Tiendas y Negocios',
    subcategoriaHint: 'Carnicerías',
    servicios: ['Carne de res', 'Pollo', 'Cerdo', 'Chorizo', 'Carnes para asar'],
  },
  {
    clave: 'barberías_estéticas',
    aliases: [
      'barberia', 'barbería', 'barberias', 'barberías',
      'estetica', 'estética', 'esteticas', 'estéticas',
      'peluqueria', 'peluquería', 'peluquerías',
      'corte de pelo', 'corte de cabello',
      'rasurado', 'rasura', 'afeitado',
      'barba', 'arreglo de barba', 'fade',
      'degradado', 'tinte', 'coloracion', 'coloración',
      'permanente', 'alaciado', 'keratina',
      'peinado', 'chino', 'rulos',
      'uñas', 'manicure', 'manicura', 'pedicure', 'pedicura',
      'depilacion', 'depilación', 'cera',
      'spa', 'masajes',
      'salon de belleza', 'salón de belleza',
      'centro de belleza', 'imagen personal',
    ],
    categoriaHint: 'Belleza y Cuidado Personal',
    subcategoriaHint: 'Barberías y Estéticas',
    servicios: [
      'Corte de cabello', 'Rasurado', 'Arreglo de barba',
      'Tinte y coloración', 'Manicure', 'Pedicure', 'Depilación',
    ],
  },
];